### ISSUE TITLE
The bump-minor-pre-major option in the workflow file is ignored

### ISSUE THREAD

**Issue by ChristianIvicevic** [google-github-actions/release-please-action#168]
After trying out the action with the following file

```yaml
name: Release
on:
  push:
    branches: [main]
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: node
          package-name: npm-test-package
          bump-minor-pre-major: true
```

I noticed that every single release starts with `v1.0.0` ignoring the `bump-minor-pre-major` flag. I expected it to start at `v0.1.0` as stated in my `package.json`.
