### ISSUE TITLE
Npm publish issue

### ISSUE THREAD

**Issue by gengjiawen** [google-github-actions/release-please-action#174]
Thanks. Now I get E404 in https://github.com/gengjiawen/monkey-rust/runs/1647197523.

I have set the token in my repo. Any other thing can cause this ?

![image](https://user-images.githubusercontent.com/3759816/103595122-9fee7d00-4f35-11eb-8fcb-ab55f631eb65.png)

![image](https://user-images.githubusercontent.com/3759816/103595100-8f3e0700-4f35-11eb-88c4-cd0881fde9c0.png)

_Originally posted by @gengjiawen in https://github.com/google-github-actions/release-please-action/issues/172#issuecomment-754320865_

**Comment by gengjiawen** [comment]
Or this because this is my first publish on npm, current action only supports update ?

Or just a npm bug ? https://github.com/npm/cli/issues/1637

**Comment by bcoe** [comment]
@gengjiawen you should be able to do the initial publication from the action, one thing that looks slightly weird to me is that there's no scheme on the URL.

You could add the stanza:

```
 - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org/'
        if: ${{ steps.release.outputs.release_created }}
```
