### ISSUE TITLE
[Feature request] append artifact to release.

### ISSUE THREAD

**Issue by gengjiawen** [google-github-actions/release-please-action#176]
I really enjoy using release-please (thanks for this project). I introduce to my electron project, which need artifact on release

My previous release like this, include binary for auto-updates.
![image](https://user-images.githubusercontent.com/3759816/103845467-18407400-50d7-11eb-9f81-51d0f5c04881.png)

But with release please, I can only get this (this will also break auto-updater for electron).

![image](https://user-images.githubusercontent.com/3759816/103845517-2f7f6180-50d7-11eb-83dd-435b19380699.png)

It would be much wonderful to use artifacts in this case.

**Comment by bcoe** [comment]
> I really enjoy using release-please (thanks for this project)

Thank you 👏 

> I introduce to my electron project, which need artifact on release

I was talking to my colleague @JustinBeckwith today, about how he'd like a version of release please that handles advanced workflows (_in his case, like publishing to npm_).

My thinking, is that it would be good to add guides in `docs/` that demonstrate complex workflows:

* `docs/npm.md`: how you wire up a GitHub action, with release-please, to publish to npm.
* `docs/electron.md`: how you wire up a GitHub action, with release-please, to publish artifacts to the release.

----

*Question:* when you're creating an electron application, how are the artifacts created, is it a step that happens, e.g., `npm run build`?

**Comment by JustinBeckwith** [comment]
FWIW, this is something [semantic-release-github](https://github.com/semantic-release/github#usage) supports.  I needed this in [linkinator](https://github.com/JustinBeckwith/linkinator/blob/master/.releaserc.json) to attach release binaries generated by `vercel/pgk` as part of the release.

**Comment by gengjiawen** [comment]
> My thinking, is that it would be good to add guides in docs/ that demonstrate complex workflows:

This looks very good to me.

> Question: when you're creating an electron application, how are the artifacts created, is it a step that happens, e.g., npm run build?

`yarn electron-build`

**Comment by Oyabi** [comment]
Hi, any update or work around on this issue?

**Comment by gengjiawen** [comment]
@chingor13 why you close this issues ? It's not deprecated.

Also cc @bcoe Is this project dead ?

**Comment by JustinBeckwith** [comment]
I also continue to need this @bcoe @chingor13  👅

**Comment by MuZhou233** [comment]
Hello everyone, I'm facing to the same issue today and now I found a way to *resolve it in my use case*. I use https://github.com/svenstaro/upload-release-action to upload artifact after a new release is created by release-please.
The following code is a simple demo. It has more limit but at least working, So it will be better if we have an official support to attach file.
If you want to see a full working demo, please check [my project](https://github.com/TuiHub/Sentinel/blob/master/.github/workflows/release-please.yml) 
```
name: release-please
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
            ... # YOUR CONFIG
  build:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.releases_created }}
    steps:
      - uses: actions/checkout@v3
      - name: Compile and release
            ... # YOUR COMPILE COMMAD
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ... # THE FILE TO ATTACH TO RELEASE
          tag: ${{ needs.release-please.outputs.tag_name }}
```
