### ISSUE TITLE
rust version not changed for workspace project

### ISSUE THREAD

**Issue by gengjiawen** [google-github-actions/release-please-action#180]
https://github.com/gengjiawen/monkey-rust/pull/28

@bcoe @fasterthanlime

**Comment by bcoe** [comment]
@gengjiawen thank you for the bug report. I'll investigate tomorrow, unless @fasterthanlime is ... faster than me.

**Comment by fasterthanlime** [comment]
So, for a cargo workspace like this, the supported workflow is to run the release-please action once per crate in your workspace.

Instead of: 

```yaml
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: rust
          package-name: release-please-action
```

You could use a build matrix, something like:

```yaml
jobs:
  crates:
    strategy:
      matrix:
        include:
          - crate: monkey-parser
            path: parser
          - crate: monkey-interpreter
            path: interpreter
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          monorepo-tags: true
          release-type: rust
          path: ${{ matrix.path }}
          package-name: ${{ matrix.crate }}
```
