### ISSUE TITLE
API rate limit exceeded

### ISSUE THREAD

**Issue by P4sca1** [google-github-actions/release-please-action#205]
I can't get `release-please` to work. The workflow fails with the following error message:
```
release-please failed: API rate limit exceeded
```

Here's my workflow file:
```yml
name: release-please

on:
  push:
    branches:
      - ci-test

jobs:
  release-please:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        app:
          - api
          - daemon
          - frontend
          - gextension-invoices
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        with:
          path: apps/${{matrix.app }}
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: ${{ matrix.app }}
          monorepo-tags: true

```
