### ISSUE TITLE
Use repo to release new versions

### ISSUE THREAD

**Issue by pragmaticivan** [google-github-actions/release-please-action#220]
It currently uses a released version of release-please-action but could be using its own head source code to insure it works before creating a new release.

It can be done like:

```
      - uses: ./ # Uses an action in the root directory
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: my-package
          default-branch: main
```

Ref: https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#example-using-a-private-action
