### ISSUE TITLE
Error: release-please failed: Not Found

### ISSUE THREAD

**Issue by rudywaltz** [google-github-actions/release-please-action#262]
I have successful release a week ago, but now (without any config change) I faced an issue
`Error: release-please failed: Not Found`
I try to rollback to some older version, but `2.19.2` also failing. I try add more information later

currently we running something like this

```
    runs-on: ubuntu-latest
    steps:
       - uses: GoogleCloudPlatform/release-please-action@v2.19.2
         with:
           token:  ********
           command: release-pr
           release-type: node
```

and

```
release-tag:
    runs-on: ubuntu-latest
    steps:
       - uses: GoogleCloudPlatform/release-please-action@v2.19.2
         with:
           token: ***
           command: github-release
           release-type: node
```
