### ISSUE TITLE
Example use with a monorepo

### ISSUE THREAD

**Issue by tjdavis3** [google-github-actions/release-please-action#286]
I am attempting to test with a simple monorepo with two projects.  A vue.js frontend and a golang backend.  I've attempted to setup an action for each along with the path.  When I do not use the `multirepo-tags: true` option I get errors.  However, when setting it to true there is never a PR created.

On a commit with a subject of: `fix(frontend): Update` the following output is received:

```
Run GoogleCloudPlatform/release-please-action@v2
  with:
    token: ***
    release-type: node
    path: frontend
    package-name: frontend
    monorepo-tags: true
    fork: false
    clean: true
    bump-minor-pre-major: false
    pull-request-title-pattern: chore${scope}: release${component} ${version}
✖ No merged release PR found
✖ Unable to build candidate
✖ pull #60 046444097948def303e3c556c6ce42470591b7bd has not yet been released
```

Is there an example of exactly how to use release-please with a monorepo and what exactly `monorepo-tags` does?
