### ISSUE TITLE
Random failures with "Cannot read property 'repository' of undefined"

### ISSUE THREAD

**Issue by ckingbailey** [google-github-actions/release-please-action#326]
### The issue
I've successfully been using Release Please to manage releases on a private repo for a few months. After using it for a little over a week, I started getting seemingly random, occassional failures with one of two messages:
- "release-please failed: Cannot read property 'repository' of undefined" _(most often)_
- "release-please failed: invalid json response body at https://api.github.com/graphql reason: Unexpected end of JSON input" _(less frequently)_

This error always occurs after the step in the logs "Unable to build candidate" (That message is expected because we don't use a setup.py or setup.cfg for the project). Initially these seemingly random failures were happening 10-20% of the time, but they've become more common. I now get a release-please failed message every 3 or 4 runs.

### Log output
Here's the relevant bit of GitHub Actions job run logs for the last failed one. The run was triggered by merging a PR with the title message "fix: Plank balance change".
```
Run GoogleCloudPlatform/release-please-action@v2
  with:
    default-branch: main
    release-type: python
    package-name: calc_models
    token: ***
    fork: false
    clean: true
    bump-minor-pre-major: false
    monorepo-tags: false
    pull-request-title-pattern: chore${scope}: release${component} ${version}
✖ No merged release PR found
✖ Unable to build candidate
Error: release-please failed: Cannot read property 'repository' of undefined
```

For comparison, logs from a successful run look like this
```
Run GoogleCloudPlatform/release-please-action@v2
✖ No merged release PR found
✖ Unable to build candidate
✔ found 2 commits since f.....d
✔ release as patch: There are 0 BREAKING CHANGES and 0 features
✖ file pyproject.toml did not exist
✔ updating CHANGELOG.md
✖ file setup.cfg did not exist
✖ file setup.py did not exist
✔ Starting GitHub PR workflow...
✔ Successfully found branch HEAD sha "6.....d".
✔ Successfully created branch at https://api.github.com/repos/sparta-science/...../git/refs/heads/release-v_._._
✔ Got the latest commit tree
✔ Successfully created a tree with the desired changes with SHA a.....f
✔ Successfully created commit. See commit at https://api.github.com/repos/sparta-science/...../git/commits/9.....b
✔ Successfully updated reference release-v_._._ to 9.....b
✔ Successfully opened pull request available at url: https://api.github.com/repos/sparta-science/...../pulls/......
✔ Successfully opened pull request: ......
✔ adding label autorelease: pending to https://github.com/sparta-science/...../pull/.....
✔ find stale PRs with label "autorelease: pending"
```

### Workflow file
This is the top of the workflow file for the GitHub Actions Workflow that runs Release Please
```yaml
name: Test, build, and deploy calc model

on:
  push:
    branches:
      - main

jobs:
  build_calcs:
    name: Build and release
    runs-on: ubuntu-20.04
    steps:
      - name: Run unit tests here
        run: echo "does nothing"
      - name: Release Please release manager
        id: release_please
        uses: GoogleCloudPlatform/release-please-action@v2
        with:
          default-branch: main
          release-type: python
          package-name: calc_models
      - name: Checkout code
        if: steps.release_please.outputs.release_created
        uses: actions/checkout@v2
      - name: Pip install dependencies
        if: steps.release_please.outputs.release_created
        run: pip3 install -r requirements.txt
.....
```

### What I've tried
Not much, since I can't reliably reproduce the issue. I haven't found any pattern in the failures. I thought it might be that large numbers of files were being changed on each commit, but that is not always the case. Some failed runs are on PRs that have 227 changed files, but others are on PRs that change only 32 files. We version control a lot of CSV files for testing, hence the large numbers of file changes.

I peaked into the Release Please index.js a bit, and I'd speculate that the "Cannot read property 'repository' of undefined" may also be coming from a GraphQL query, one that succeeded with an empty response rather than failing on unexpected input. But I'm only speculating there.

#### Update
The "Cannot read property 'repository'" error made me think that the `github` context object might be missing from those jobs that failed with that error, but I have confirmed that the `github` context object and its `repository` property are present and contain the expected value on those jobs that failed with this error.
