### ISSUE TITLE
Error: release-please failed: Could not find requested path: npm-shrinkwrap.json

### ISSUE THREAD

**Issue by christian-hawk** [google-github-actions/release-please-action#337]
Using the following yaml
```yaml
on:
  push:
    branches:
      - master
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: release-please-action
```

I get:
```
Run GoogleCloudPlatform/release-please-action@v2
  with:
    token: ***
    release-type: node
    package-name: release-please-action
    fork: false
    clean: true
    bump-minor-pre-major: false
    monorepo-tags: false
    pull-request-title-pattern: chore${scope}: release${component} ${version}
⚠ No merged release PR found
✖ Unable to build candidate
✔ found 8 commits since 0803e6e07195ed7f55cc9df48e6c8dc59c10a290
✔ release as minor: There are 0 BREAKING CHANGES and 3 features
✔ updating package-lock.json from 1.0.0 to 1.1.0
Error: release-please failed: Could not find requested path: npm-shrinkwrap.json
```

I have found nothing about it. By the way, the repo is https://GitHub.com/GluuFederation/inbound-saml
