### ISSUE TITLE
append extra file changes in pull request

### ISSUE THREAD

**Issue by gengjiawen** [google-github-actions/release-please-action#343]
I have other files to squash into the release pr. E.g version number in docs.

Is there an easy way to do this ? My thought is to add an `extra-files` to do this ?

```yml
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          package-name: monkey-rust
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: rust
          extra-files: node patch-my-file.js		
```

This also will fix https://github.com/google-github-actions/release-please-action/issues/180

My current workaround is to change https://github.com/gengjiawen/monkey-rust/pull/57 directly, but it's cumbersome.

cc @bcoe
