### ISSUE TITLE
Can I change the release name with a custom name or add a prefix before v1.0.0?

### ISSUE THREAD

**Issue by dancardonaortiz** [google-github-actions/release-please-action#369]
I'm trying to change the package name to another but it always shows the name of the package.json. This is my release workflow

```yaml
on:
  push:
    branches:
      - master
name: Release
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Release
        uses: GoogleCloudPlatform/release-please-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: Code Hub Web 214.6
```

I don't know if it's possible to do that or just put a prefix there

![image](https://user-images.githubusercontent.com/88685065/134413346-74cecc39-e9ae-425c-8833-db6b3578df3d.png)
