### ISSUE TITLE
Action not creating release PR when alternate src/ path provided

### ISSUE THREAD

**Issue by mountaindude** [google-github-actions/release-please-action#378]
Using the Release-please action in this repo: https://github.com/ptarmiganlabs/butler-sheet-icons

The same config that works in other repos just won't work in this one. Which is strange.
Release-please used to work for this repo too, but stopped working sometime since last release (a few weeks ago).
Can't recall changing anything relating to release-please.
Can more verbose logging be turned on for the Release Please action to show what's going on?

The action triggers fine when I push something to `main` branch, but then the action doesn't recognise any of the commits that have been made (fix: , refactor: etc).

The action log looks like this:

```
Run GoogleCloudPlatform/release-please-action@v2
  with:
    token: ***
    release-type: node
    package-name: butler-sheet-icons
    path: src
    default-branch: main
    fork: false
    clean: true
    bump-minor-pre-major: false
    bump-patch-for-minor-pre-major: false
    monorepo-tags: false
    pull-request-title-pattern: chore${scope}: release${component} ${version}
  env:
    GITHUB_REF: refs/heads/main
    GITHUB_TOKEN: ***
(node:1519) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
⚠ No merged release PR found
✖ Unable to build candidate
✔ found 13 commits since 11029d24afd0cf19cb48552a40d56cf668a24368
✔ release as patch: There are 0 BREAKING CHANGES and 0 features
⚠ no user facing commits found since 11029d24afd0cf19cb48552a40d56cf668a24368
```

The workflow looks like this ([link](https://github.com/ptarmiganlabs/butler-sheet-icons/blob/main/.github/workflows/release-please.yml)):

```
name: release-please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    env:
      GITHUB_REF: ${{ github.ref }}
      # GITHUB_USER: ${{ secrets.GITHUB_USER }}
      GITHUB_TOKEN: ${{ secrets.PAT }}
    steps:
      - name: Show github.ref
        run: echo "$GITHUB_REF"

      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        if: |
          github.repository_owner == 'ptarmiganlabs'
        with:
          token: ${{ env.GITHUB_TOKEN }}
          release-type: node
          package-name: butler-sheet-icons
          path: src
          default-branch: main

      - name: Show output from Release-Please
        if: ${{ steps.release.outputs.release_created }}
        run: |
          echo "release_created: ${{ steps.release.outputs.release_created }}"
          echo "upload_url: ${{ steps.release.outputs.upload_url }}"
          echo "html_url: ${{ steps.release.outputs.html_url }}"
          echo "tag_name: ${{ steps.release.outputs.tag_name }}"
          echo "major: ${{ steps.release.outputs.major }}"
          echo "minor: ${{ steps.release.outputs.minor }}"
          echo "patch: ${{ steps.release.outputs.patch }}"
          echo "sha: ${{ steps.release.outputs.sha }}"
          echo "pr: ${{ steps.release.outputs.pr }}"
```
