### ISSUE TITLE
docs: emphasize importance of using your own token for subsequent GitHub action workflows

### ISSUE THREAD

**Issue by chingor13** [google-github-actions/release-please-action#404]
### TL;DR

There are limitations to when other GitHub actions are triggered if you are using the default `GITHUB_TOKEN`

https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token

We should emphasize the fact that you probably want to use your own credentials if you are using GitHub actions for other things on the created pull requests and/or releases.

### Action YAML

```yaml
N/A
```

**Comment by bowentan** [comment]
Are there any example configuration using PAT to trigger another workflow? I tried many many many times but I still couldn't trigger a workflow which should be triggered by a tag push... My configurations are below:

```yaml
- The triggering workflow -
name: Release please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        env:
          github-token: ${{ secrets.TEST }}
        id: release
        with:
          release-type: python
          prerelease: true
      - uses: actions/checkout@v3
        env:
          github-token: ${{ secrets.TEST }}
      - name: tag major and minor versions
        env:
          github-token: ${{ secrets.TEST }}
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git remote add gh-token "https://${{ secrets.GITHUB_TOKEN }}@github.com/google-github-actions/release-please-action.git"
          git tag -d v${{ steps.release.outputs.major }} || true
          git tag -d v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
          git push origin :v${{ steps.release.outputs.major }} || true
          git push origin :v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
          git tag -a v${{ steps.release.outputs.major }} -m "Release v${{ steps.release.outputs.major }}"
          git tag -a v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} -m "Release v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}"
          git push origin v${{ steps.release.outputs.major }}
          git push origin v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}
```
```yaml
- The triggered workflow -
name: On create tag

on:
  push:
    tags:
      - "*"
jobs:
  on-create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo hello
```

Can anyone help me out of this issue?
