### ISSUE TITLE
Initial version 0.1.0 is ignored

### ISSUE THREAD

**Issue by maprokes** [google-github-actions/release-please-action#425]
### TL;DR

When I use the manifest to set the initial version to 0.1.0 it is ignored when a new PR is created even though I have `bump-minor-pre-major: true` and `bump-patch-for-minor-pre-major: true`

### Expected behavior

Expected next version is v0.1.1

### Observed behavior

Next version in the PR is v1.0.0

### Action YAML

```yaml
name: Release
on:
    push:
        branches:
            - master

jobs:
    release-please:
        name: Prepare Release notes
        runs-on: ubuntu-latest
        outputs:
            released: ${{ steps.release-please.outputs.release_created }}
            tag: ${{ steps.release-please.outputs.tag_name }}
        steps:
            - id: release-please
              uses: GoogleCloudPlatform/release-please-action@v3
              with:
          # A repository with a version.txt and a CHANGELOG.md
                  changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'
                  release-type: simple
                  package-name: package1
                  bump-minor-pre-major: true
                  bump-patch-for-minor-pre-major: true
```

### Log output

```text
Run GoogleCloudPlatform/release-please-action@v3
  with:
    changelog-types: [{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]
    release-type: simple
    package-name: package1
    bump-minor-pre-major: true
    bump-patch-for-minor-pre-major: true
    config-file: release-please-config.json
    manifest-file: .release-please-manifest.json
    token: ***
    fork: false
    clean: true
    monorepo-tags: false
    draft: false
    draft-pull-request: false
✔ Looking for latest release on branch: master with prefix: 
⚠ Could not find releases.
✔ Building releases
✔ Building strategies by path

✔ Looking for latest release on branch: master with prefix: 
⚠ Could not find releases.
✔ Building pull requests
✔ Building strategies by path
✔ Collecting release commit SHAs
⚠ Could not find releases.
⚠ Expected 1 releases, only found 0
✔ Collecting commits since all latest releases
✔ Splitting 20 commits by path
✔ Building candidate release pull request for path: .
⚠ No latest release pull request found.
✔ Considering: 14 commits
✔ Looking for open release pull requests
✔ found 0 open release pull requests.
⚠ file version.txt did not exist
✔ Starting GitHub PR workflow...
✔ Successfully found branch HEAD sha "12345678".
✔ Successfully created branch at https://api.github.com/repos/test-repo/git/refs/heads/release-please--branches--master
✔ Got the latest commit tree
✔ Successfully created a tree with the desired changes with SHA ---
✔ Successfully created commit. See commit at https://api.github.com/repos/org/test-repo/git/commits/12345678
✔ Successfully updated reference release-please--branches--master to 12345678
✔ Successfully opened pull request available at url: https://api.github.com/repos/org/test-repo/pulls/30.
✔ Successfully opened pull request: 30.
✔ Successfully added labels autorelease: pending to issue: 30
```

### Additional information

When I installed the release-please locally and run it with same values, it created the expected version:
```
release-please --version
13.4.4
```
```
release-please release-pr --token=$PAT_TOKEN --repo-url=org/test-repo
```
`.release-please-manifest.json`
```
{
  ".": "0.1.0"
}

```
`release-please-config.json`
```
{
  "release-type": "simple",
  "bump-minor-pre-major": true,
  "bump-patch-for-minor-pre-major": true,
  "changelog-sections": [
    {
      "type": "feat",
      "section": "Features",
      "hidden": false
    },
    {
      "type": "fix",
      "section": "Bug Fixes",
      "hidden": false
    },
    {
      "type": "chore",
      "section": "Miscellaneous",
      "hidden": false
    }
  ],
  "packages": {
    ".": {
      "packageName": "test-repo",
      "draft": false,
      "prerelease": false,
      "bumpMinorPreMajor": true,
      "bumpPatchForMinorPreMajor": true,
      "changelogPath": "CHANGELOG.md",
      "versioning": "default"
    }
  }
}
```
