### ISSUE TITLE
Documentation for manifest release output example

### ISSUE THREAD

**Issue by Zoramite** [google-github-actions/release-please-action#429]
### TL;DR

When using a manifest the action outputs track the release information per package, but there is no documentation on how that is presented to the user.

### Detailed design

It appears that output after creating releases should be outputting the [package specific release information](https://github.com/google-github-actions/release-please-action/blob/main/index.js#L162). But what does that look like in the final output?

For example:

```yaml
- name: Deploy package-a docs to prod
  # Code shows it uses the path for the release.
  # if: ${{ steps.release.outputs.${path}--release_created }}
  # But if the package is in a sub directory do you use a slash?
  # if: ${{ steps.release.outputs.packages/package-a--release_created }}
  # Or does it transform the directory and output differently?
  # if: ${{ steps.release.outputs.packages.package-a--release_created }}
  run: echo "Deploy package-a docs to prod... ${{ steps.release.outputs.packages.package-a--tag_name }}"
```
