### ISSUE TITLE
The "pull-request-title-pattern" option is not respected

### ISSUE THREAD

**Issue by kettanaito** [google-github-actions/release-please-action#436]
### TL;DR

The custom value for the `pull-request-title-pattern` option in the workflow has no effect: the default pull request title is being used instead.

### Expected behavior

The action uses the pattern provided as the value of the `pull-request-title-pattern` option in the workflow file.

### Observed behavior

The default pull request title pattern is used anyway.

### Action YAML

```yaml
name: CI
on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest-pr
          pull-request-title-pattern: "chore(${component}): release ${version}"
```

### Log output

```text
No log output.
```

### Additional information

I've also tried setting the `group-pull-request-title-pattern` option in the `release-please-config.json`, which resulted in no change: the default pattern is always used.

It's worth mentioning I'm integrating this in a monorepo, maybe it has something to do with the issue. The release config is still in the root of the repo, just like GitHub workflows.
