### ISSUE TITLE
Action fails to find latest releases in GitHub Enterprise

### ISSUE THREAD

**Issue by tleibovichverint** [google-github-actions/release-please-action#442]
### TL;DR

I'm running on Enterprise edition, any tests using this action are failing with:   
`Looking for latest release on branch: main with prefix: .`
`Error: release-please failed: `

** Edited with the correct version

### Action YAML

```yaml
name: release-please
on:
   push:
      branches:
         - main
jobs:
   release-please:
      runs-on: [self-hosted]
      steps:
         - uses: google-github-actions/release-please-action@v3.1.2
           with:
            token: ${{ secrets.GITHUB_TOKEN }}
            release-type: simple
            version-file: "./version.txt"
            package-name: release-please-action
            default-branch: main
            github-api-url: https://myserver.com
            github-graphql-url: https://myserver.com
```

### Log output

```text
Run google-github-actions/release-please-action@v[3.1.2]
  with:
    token: ***
    release-type: simple
    version-file: ./version.txt
    package-name: release-please-action
    default-branch: main
    github-api-url: https://myserver.com
    github-graphql-url: https://myserver.com
    fork: false
    clean: true
    bump-minor-pre-major: false
    bump-patch-for-minor-pre-major: false
    monorepo-tags: false
    pull-request-title-pattern: chore${scope}: release${component} ${version}
Looking for latest release on branch: main with prefix: 
Error: release-please failed:
```
