### ISSUE TITLE
monorepo tags broken in v3

### ISSUE THREAD

**Issue by wraithgar** [google-github-actions/release-please-action#457]
### TL;DR

When we use v3 of this action our workspace PRs pick up the version from our root project, not the workspace.

### Expected behavior

PRs for workspaces correctly find the current version from monorepo tags.

### Observed behavior

The PR that is made uses the version from the root tag.  Here is an erroneous PR that correctly makes the changelog for arborist (a workspace) but tags it as if the root project (npm itself) is the version arborist is on

https://github.com/npm/cli/pull/4648/files

### Action YAML

```yaml
This file is automatically added by @npmcli/template-oss. Do not edit.

name: Release Please - @npmcli/arborist

on:
  push:
    paths:
      - workspaces/arborist/**
    branches:
      - main
      - latest

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          monorepo-tags: true
          path: workspaces/arborist
          changelog-types: >
            [
              {"type":"feat","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"docs","section":"Documentation","hidden":false},
              {"type":"deps","section":"Dependencies","hidden":false},
              {"type":"chore","hidden":true}
            ]
```

### Additional information

If we downgrade to v2 in another repo that doesn't use workspaces, it is unable to see any of the releases v3 made.
If we pin to v3.0.0-v3.1.0, the pr it makes is always `v1.0.0`, it is in release-please-action v3.1.1 this behavior starts.
