### ISSUE TITLE
Release please fails after moving a repository to a new organization

### ISSUE THREAD

**Issue by johanneskoester** [google-github-actions/release-please-action#479]
### TL;DR

Release-please was working fine. After moving the repo to a new organization, it fails suddenly.

### Expected behavior

working without error as nothing has been changed

### Observed behavior

Fails with an error message (see log below)

### Action YAML

```yaml
on:
  push:
    branches:
      - main

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:

      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          release-type: python
          package-name: yte

      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}

      - uses: actions/setup-python@v2
        if: ${{ steps.release.outputs.release_created }}
        with:
          python-version: "3.9"

      - name: Setup poetry
        if: ${{ steps.release.outputs.release_created }}
        uses: abatilo/actions-poetry@v2.0.0

      - name: Install Dependencies using Poetry
        if: ${{ steps.release.outputs.release_created }}
        run: poetry install
      
      - name: Publish to PyPi
        if: ${{ steps.release.outputs.release_created }}
        env:
          PYPI_USERNAME: __token__
          PYPI_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish --build --username $PYPI_USERNAME --password $PYPI_PASSWORD
```

### Log output

```text
Run GoogleCloudPlatform/release-please-action@v3
  with:
    release-type: python
    package-name: yte
    token: ***
    fork: false
    clean: true
    bump-minor-pre-major: false
    bump-patch-for-minor-pre-major: false
    monorepo-tags: false
    draft: false
    draft-pull-request: false
✔ Looking for latest release on branch: main with prefix: 
✔ Building releases
✔ Building strategies by path
✔ Building release for path: .
Error: release-please failed: Resource not accessible by integration
```

### Additional information

The repo was moved to a new organization.
