### ISSUE TITLE
Version calculation includes package-name as prefix as of v3.2.4

### ISSUE THREAD

**Issue by tshowers-bt** [google-github-actions/release-please-action#491]
### TL;DR

Existing projects are having their versions reset to 1.0.0 because the `package-name` is being included as a prefix when searching for the latest released version. I've left [a comment](https://github.com/googleapis/release-please/commit/628a562a21245ed02546aa0c40c97a0e3d50a0c7#r73961429) on what I believe to be the offending code change.

### Expected behavior

Projects whose workflows have not changed should continue to continue to calculate versions as they have with previous `v3` versions.

### Observed behavior

Projects are including `package-name` as a prefix when searching for the latest release version and therefore determining there have been no releases.

### Action YAML

```yaml
name: "Release Please Build"

on:
  push:
    branches: [master]

env:
  PACKAGE_NAME: Eventing.Kafka

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Release Please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          package-name: ${{ env.PACKAGE_NAME }}
```
