### ISSUE TITLE
New release PR is opened after merging upgrade

### ISSUE THREAD

**Issue by shubha-rajan** [google-github-actions/release-please-action#496]
### TL;DR

We merged a PR to upgrade release-please to v3.2.5 and a second release PR was opened. We've noticed this behavior in multiple repos.

cc: @kurtisvg

### Expected behavior

If there's a release PR currently open, upgrading the github action shouldn't open a new one.

### Observed behavior

A new PR was opened.
<img width="1337" alt="image" src="https://user-images.githubusercontent.com/19631367/169596884-17ad4adc-a20e-43ed-97b5-b3d587d2f394.png">

### Action YAML

```yaml
name: release-please
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3.2.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          package-name: cloud-sql-go-connector
```

### Log output

```text
Run GoogleCloudPlatform/release-please-action@v3.2.5
  with:
    token: ***
    release-type: simple
    package-name: cloud-sql-go-connector
    fork: false
    clean: true
    bump-minor-pre-major: false
    bump-patch-for-minor-pre-major: false
    monorepo-tags: false
    draft: false
    draft-pull-request: false
✔ Looking for latest release on branch: main with prefix: cloud-sql-go-connector
✔ Building releases
✔ Building strategies by path

✔ Looking for latest release on branch: main with prefix: cloud-sql-go-connector
✔ Building pull requests
✔ Building strategies by path
✔ Collecting release commit SHAs
✔ Collecting commits since all latest releases
✔ Splitting 14 commits by path
✔ Building candidate release pull request for path: .
✔ Considering: 16 commits
✔ Looking for open release pull requests
✔ found 1 open release pull requests.
✔ Looking for snoozed release pull requests
✔ found 0 snoozed release pull requests.
⚠ file .release-please-manifest.json did not exist
✔ Starting GitHub PR workflow...
✔ Successfully found branch HEAD sha "462ba0a36b313d66830f95e6fc9b829255254174".
✔ Successfully created branch at https://api.github.com/repos/GoogleCloudPlatform/cloud-sql-go-connector/git/refs/heads/release-please--branches--main--components--cloud-sql-go-connector
✔ Got the latest commit tree
✔ Successfully created a tree with the desired changes with SHA bf1a4d01faf10fa6ec8a0f2511277e34c9fd618e
✔ Successfully created commit. See commit at https://api.github.com/repos/GoogleCloudPlatform/cloud-sql-go-connector/git/commits/3cca13e3647cbd2fca932a10c89fef795fc8c3a8
✔ Successfully updated reference release-please--branches--main--components--cloud-sql-go-connector to 3cca13e3647cbd2fca932a10c89fef795fc8c3a8
✔ Successfully opened pull request available at url: https://api.github.com/repos/GoogleCloudPlatform/cloud-sql-go-connector/pulls/203.
✔ Successfully opened pull request: 203.
✔ Successfully added labels autorelease: pending to issue: 203
```
