### ISSUE TITLE
Help Wanted: How can I get outputs from monorepo

### ISSUE THREAD

**Issue by AnzhiZhang** [google-github-actions/release-please-action#509]
I used matrix for monorepos, here is my workflow:
```
  release-please-release:
    runs-on: ubuntu-latest
    name: Release Please Release
    needs: change-finder
    if:  ${{ needs.change-finder.outputs.changed == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        plugin: ${{ fromJson(needs.change-finder.outputs.plugins) }}

    steps:
      - name: Release Please Release
        uses: google-github-actions/release-please-action@v3
        id: release_please_release
        with:
          release-type: simple
          package-name: ${{ matrix.plugin }}
          path: ${{ matrix.plugin }}
          monorepo-tags: true
          command: github-release
          pull-request-title-pattern: 'chore${scope}: 🔖 release${component} ${version}'
```

I notified outputs for monorepo will have a prefix of package name.
![image](https://user-images.githubusercontent.com/37402126/175465956-2f1d5957-33ad-4f84-a436-bc9454131a03.png)

I tried following ways to get outputs of monorepo, but they did not working, I also searched issues and google for help, but I did not find solutions.
```text
${{ steps.release_please_pr.outputs.${{matrix.plugin}}--release_created' }}
${{ format('steps.release_please_pr.outputs.{0}--release_created', matrix.plugin) }}
```

Is there any way to get outputs with monorepo dynamic package names?
