### ISSUE TITLE
Action makes wrong commit URL in GitHub Enterprise

### ISSUE THREAD

**Issue by NoUnique** [google-github-actions/release-please-action#525]
### TL;DR

Action makes commit URL as `github.com` instead of `GITHUB_SERVER_URL` in GitHub Enterprise

### Expected behavior

I expect PR contains commit titles with a link of correct commit URL

### Observed behavior

PR contains commit titles with commit URL start with `https://github.com` instead of a host of Github Enterprise Server

### Action YAML

```yaml
name: release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release-charts:
    runs-on: [ self-hosted ]
    continue-on-error: true
    strategy:
      matrix:
        charts: [
          "local-volume-provisioner",
          SOMETHING ELSE...
        ]
    steps:
      - uses: ACTION_OWNER/release-please-action@v3
        with:
          github-api-url: GITHUB_SERVER_URL/api/v3
          github-graphql-url: GITHUB_SERVER_URL/api
          package-name: ${{ matrix.charts }}
          path: ${{ matrix.charts }}
          release-type: helm
          monorepo-tags: true
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          pull-request-title-pattern: "chore: release${component} ${version}"
          changelog-types: '[
            {"type":"feat","section":"Features","hidden":false},
            {"type":"fix","section":"Bug Fixes","hidden":false},
            {"type":"chore","section":"Miscellaneous","hidden":false}
          ]'
```

### Additional information

Pull Request Body

```markdown
:robot: I have created a release *beep* *boop*
---


## 2.6.0-alpha.1 (2022-07-13)


### Features

* update chart to db349d78bdaa543a2fc5a3a8aba1a7ece1420570 ([0bdf180](https://github.com/OWNER/REPO/commit/0bdf1807215459b81aefe018e825bd351ec2cf5b))

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).
```

Since github enterprise API returns correct commit URL, I think it is not a fault of the API.

```json
{
  "sha": "b973cd9b0703f9ab1109df4241ecc0dfd1cc6480",
  "node_id": "MDY6Q29tbWl0MjU4ODAyOmI5NzNjZDliMDcwM2Y5YWIxMTA5ZGY0MjQxZWNjMGRmZDFjYzY0ODA=",
  "commit": {
    "author": {
      "name": "NAME",
      "email": "EMAIL",
      "date": "2022-07-13T13:52:59Z"
    },
    "committer": {
      "name": "GitHub Enterprise",
      "email": "ENTERPRISE_MAIL",
      "date": "2022-07-13T13:52:59Z"
    },
    "message": "COMMIT_MESSAGE",
    "tree": {
      "sha": "1e9c651749ff8bd66de68be843c702c44525dc3e",
      "url": "GITHUB_SERVER_URL/api/v3/repos/OWNER/REPO/git/trees/1e9c651749ff8bd66de68be843c702c44525dc3e"
    },
    "url": "GITHUB_SERVER_URL/api/v3/repos/OWNER/REPO/git/commits/b973cd9b0703f9ab1109df4241ecc0dfd1cc6480",
    "comment_count": 0,
    "verification": {
      "verified": false,
      "reason": "unsigned",
      "signature": null,
      "payload": null
    }
  }
}
```
