### ISSUE TITLE
Resolving of latest version using multiple release branches unexpected

### ISSUE THREAD

**Issue by wolf-michl** [google-github-actions/release-please-action#528]
### TL;DR

When using multiple release branches the resolving of the latest tag is done from the current branch instead of from the whole repository.

### Expected behavior

We are experiencing issues when using multiple release branches.
According to [supporting multiple release branches](https://github.com/google-github-actions/release-please-action#supporting-multiple-release-branches) multiple branches are supported. Currently we are adding `default-branch: ${{ github.ref_name }}` when running on a release branch to ensure that we support all created release branches.
We expected release-please to resolve the version from the whole repository. Otherwise we are not able to use it, as we are currently absolutely locked into using multiple release branches at the same time.

### Observed behavior

The problem is that the latest version is seamingly resolved from the current release branch, which isn't what we need. We may have multiple release branches at the same time, so one may have a newer tag than the one which release-please currently runs for.

### Action YAML

```yaml
name: Release flow test
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - release-please*
  pull_request: {}

jobs:
  release-please:
    runs-on: ubuntu-latest
    name: Release please
    outputs:
      release_created: ${{ steps.release_please.outputs.release_created }}
      tag_name: ${{ steps.release_please.outputs.tag_name }}
    steps:
      - name: Release please
        id: release_please
        if: startsWith(github.ref, 'refs/heads/release-')
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: go
          package-name: prototype-versioning
          default-branch: ${{ github.ref_name }}
```

### Additional information

We tried some workarounds for this:

1. After the release was created we merged the release branch using the ours strategy. This was to add the created tag to the default branch where release branches are branched from. This worked, but had the problem of still needing to use a release-as commit to bump versions in release branches, that were created before the latest tag was added to the default branch.
2. After release-please created a PR we create a release-as commit on our default branch with a new version which should be used by release-please in the future (for the next release branch). This works for the version, but not for the changelog, as the commits will still be resolved the same way. This could probably solved using last-release-sha, which isn't something we can add to the action, only in the manifest...
