### ISSUE TITLE
Release Please action taking a long time to complete

### ISSUE THREAD

**Issue by alansouzati** [google-github-actions/release-please-action#535]
### TL;DR

After adding an iconography package, release actions take a long time to make a decision and thus complete the action task. Previously the task would complete in less than 1 minute and now it is taking 6m+.

The icons are based on the material set and that package has over 20k files.

### Expected behavior

We are able to complete release please actions in an acceptable time

### Observed behavior

The task is taking a long time to complete

### Action YAML

```yaml
name: Release Tracker New

on:
  push:
    branches:
      - main

env:
  NPM_AUTH_TOKEN: ${{ secrets.GH_PACKAGE_PUBLISH }}

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          token: ${{secrets.GH_PACKAGE_PUBLISH}}
```

### Log output

```text
✔ Collecting commits since all latest releases
⚠ Found release tag with component 'bungalow-icons-material', but not configured in manifest
⚠ Found 3000 files. This may not include all the files.
⚠ Found 3000 files. This may not include all the files.
✔ PR #104 has many files, backfilling
⚠ Found 3000 files. This may not include all the files.
✔ PR #102 has many files, backfilling
⚠ Found 3000 files. This may not include all the files.
```

### Additional information

I even tried to remove the icon package from the release please configuration but still, it is seems it is getting hung up on the fact the monorepo has a package with 20k files in it.

I also tried to use a fixed sha for both `bootstrap-sha` and `last-release-sha` but no change in completion time for the release please task.
