### ISSUE TITLE
dart pubspec version is not bumping

### ISSUE THREAD

**Issue by burhankhanzada** [google-github-actions/release-please-action#540]
### TL;DR

first of all its directly creates a release to v.1.0.0 by ignoring the version defined in pubspec which is already reported in issue #425 . 
then its not updating pubspec version at all.
for example:
version: 0.1.0+1

### Expected behavior

after a fix commit

version: 0.1.1+2

### Action YAML

```yaml
name: release-please
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3.1.2
        with:
          release-type: dart
          package-name: release-please-action
```
