### ISSUE TITLE
confusion in command default value and its ussage

### ISSUE THREAD

**Issue by burhankhanzada** [google-github-actions/release-please-action#541]
### TL;DR

First of in the Configuration table text says defaults to running both while there is four option with its value so which two are is its referring to?

Secondly, i want try the manifest method to define my initial version as a work around of my issue #540

so first i created repo on git and clone then run this  bootstrap command with initial version

```cmd
release-please bootstrap --repo-url <link> --token <token> --release-type simple --initial-version 0.0.1
```
and its created pr with release-please-config.json and .release-please-manifest.json.

then i created release-please action workflow then when i push code action runs but says releae-please failed not found

```
Run google-github-actions/release-please-action@v3.1.[2](https://github.com/burhankhanzada/test1/runs/7617107817?check_suite_focus=true#step:2:2)
  with:
    release-type: simple
    command: manifest
    token: ***
    fork: false
    clean: true
    bump-minor-pre-major: false
    bump-patch-for-minor-pre-major: false
    monorepo-tags: false
    draft: false
    draft-pull-request: false
✔ Building pull requests
✔ Building strategies by path
Error: release-please failed: Not Found
```

### Action YAML

```yaml
name: release-please
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3.1.2
        with:
          release-type: simple
          command: manifest
```
