### ISSUE TITLE
Inconsistent release-note line items with squash merges

### ISSUE THREAD

**Issue by dkarkar92** [google-github-actions/release-please-action#545]
### TL;DR

When squash-merging to main, the release-notes sometimes contain PR title + commits, and sometimes only the PR title (not commits). I can't understand why, and I don't see a way to control what is added. 

### Expected behavior

Either only the PR titles should be added, or PR title + all commits. 

### Observed behavior

See screenshot below. 3 PRs total. 2 have 1 commit each that was squashed. And the last one is about 9 commits that was squashed. The 9 commit PR only contains the PR title in the notes, but the single commit squashes contain the PR + the individual commit. 

![Screen Shot 2022-08-04 at 3 43 07 PM](https://user-images.githubusercontent.com/3672996/182939259-a3c9626c-8790-478f-82a1-bc2724b384a4.png)

### Action YAML

```yaml
on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Read commit-types.json from configs and output for use in changelog-types
        id: changelog-types-output
        run: |
          echo "::set-output name=COMMIT_TYPES_STR::$(
            cat configs/commit-types.json| jq -r tostring
          )"

      - uses: google-github-actions/release-please-action@v3.2.9
        with:
          release-type: node
          package-name: strategy-application
          token: ${{ secrets.RELEASE_TOKEN }}
          changelog-types: ${{ steps.changelog-types-output.outputs.COMMIT_TYPES_STR }}
```

### Additional information

Any idea on why single commit squashes show both commits in the notes, while multiple commit squashes only show the PR title? It's actually less intuitive when a single commit squash is shown twice. The PR title encapsulates what that one commit was anyway.
