### ISSUE TITLE
command manifest ignore draft PR and custom labels

### ISSUE THREAD

**Issue by sswastioyono18** [google-github-actions/release-please-action#604]
### TL;DR

```
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          draft-pull-request: "true"
          labels: "be-autorelease: pending"
          release-labels: "be-autorelease: tagged"
```

when I use this action for monorepo, the pull request is not a draft anymore and labels config not applied
However, when I am not specifying `command manifest`, the draft pull request config works and label works

Do I have to specify this inside the manifest?if yes how to specify it because at the moment it doesn't do anything if I put it inside the manifest as well

### Expected behavior

draft pull request works and custom labels work

### Action YAML

```yaml
on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          draft-pull-request: "true"
          labels: "be-autorelease: pending"
          release-labels: "be-autorelease: tagged"
```
