### ISSUE TITLE
Option include-v-in-tag not respected for github release name

### ISSUE THREAD

**Issue by maroony** [google-github-actions/release-please-action#605]
### TL;DR

When setting option 

```yml
include-v-in-tag: false
```

there is no `v` prefix in the tag name as expected. But the github release name contains the `v`-prefix!

### Action YAML

```yaml
on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.MY_TOKEN }}
          include-v-in-tag: false
          release-type: node
          package-name: release-please-action
```
