### ISSUE TITLE
on:release types: created does not fire after release-please issues a new release

### ISSUE THREAD

**Issue by shinokada** [google-github-actions/release-please-action#612]
### TL;DR

I have the following yml:

```
name: NPM Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
...
...
```

I'm expecting to run this file after release-please creates a new release.
But it doesn't fire after release-please action but when I physically release it, it runs.

Is it possible to run this GitHub action after release-please issues a new release?
If is so, how?

### Expected behavior

mentioned as above

### Observed behavior

mentioned as above

### Action YAML

```yaml
# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: NPM Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run package
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
```

### Log output

```text
No outputs since it doesn't run.
```
