### ISSUE TITLE
Doc improvement idea: explicit required GITHUB_TOKEN permissions documented

### ISSUE THREAD

**Issue by stutommi** [google-github-actions/release-please-action#620]
### TL;DR

When dealing with with GITHUB_TOKEN permissions in workflow yml for OIDC, release-please breaks down with multiple `Resource not accessible by integration`-errors. without explicit permissions in yml-file. the action works fine.

Would be great if the exact permission-requirements would be documented in the main README.md in this repo. :)

### Detailed design

Using OIDC within an workflow, one has to put explicit permissions:
```yml
permissions:
      id-token: write
      contents: read
```
When this is done in the same workflow where release-please would be defined as following:
```yml
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
```
The result is below
_______________
✔ Looking for latest release on branch: main with prefix: release-please-action
Error: release-please failed: Request failed due to following response errors:
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 - Resource not accessible by integration
 ________________
