### ISSUE TITLE
`release-please-action` not triggering other GitHub Actions

### ISSUE THREAD

**Issue by germolinal** [google-github-actions/release-please-action#643]
### TL;DR

So, I have this `Build` action, which I want to use as checks before merging. The action is called when I create a PR, but not after `release-please` creates a PR. This means I cannot keep those as necessary checks before merging. 

Any clue why this is?

```yaml
name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  CARGO_TERM_COLOR: always

jobs:  
  build_default:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v3   
    - name: Build
      run: cargo build --verbose
  build_float:    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1      
    - name: Build Float
      run: cargo build --verbose --features float 
```

### Expected behavior

1. PR the Main branch --> trigger actions (checks)
2. Checks all right --> merge
3. Merge --> `release-please` creates a release and a PR
4. PR --> actions run and checks are checked. (THIS IS WHAT DOES NOT WORK)
5. Merge.

### Action YAML

```yaml
on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: rust
          package-name: release-please-action
```

### Log output

```text
Run google-github-actions/release-please-action@v3
  with:
    release-type: rust
    package-name: release-please-action
    token: ***
    fork: false
    clean: true
    bump-minor-pre-major: false
    bump-patch-for-minor-pre-major: false
    changelog-host: https://github.com
    github-api-url: https://api.github.com
    github-graphql-url: https://api.github.com/graphql
    monorepo-tags: false
✔ Looking for latest release on branch: main with prefix: release-please-action
⚠ Could not find releases.
✔ Building releases
✔ Building strategies by path

✔ Looking for latest release on branch: main with prefix: release-please-action
⚠ Could not find releases.
✔ Building pull requests
✔ Building strategies by path
✔ Collecting release commit SHAs
⚠ Could not find releases.
⚠ Expected 1 releases, only found 0
⚠ Missing 1 paths: .
⚠ No version for path .
⚠ Expected 1 releases, only found 0
✔ Collecting commits since all latest releases
✔ Splitting 153 commits by path
✔ Building candidate release pull request for path: .
⚠ No latest release pull request found.
✔ Considering: 1 commits
✔ single crate found, updating Cargo.toml
✔ Looking for open release pull requests
✔ found 0 open release pull requests.
✔ Looking for snoozed release pull requests
✔ found 0 snoozed release pull requests.
⚠ file Cargo.lock did not exist
⚠ file .release-please-manifest.json did not exist
✔ Starting GitHub PR workflow...
✔ Successfully found branch HEAD sha "3becf05e86715ef76e4b7dbaa0da7fd833083efb".
✔ Successfully created branch at https://api.github.com/repos/SIMPLE-BuildingSimulation/heat/git/refs/heads/release-please--branches--main--components--release-please-action
✔ Got the latest commit tree
✔ Successfully created a tree with the desired changes with SHA 8c2b0fb9308e81f85fcb7cdccba4ae402dc20920
✔ Successfully created commit. See commit at https://api.github.com/repos/SIMPLE-BuildingSimulation/heat/git/commits/163c6c5aa18211cfcfe4ba41c177c38b7f719859
✔ Updating reference heads/release-please--branches--main--components--release-please-action to 163c6c5aa18211cfcfe4ba41c177c38b7f719859
✔ Successfully updated reference release-please--branches--main--components--release-please-action to 163c6c5aa18211cfcfe4ba41c177c38b7f719859
✔ Successfully opened pull request available at url: https://api.github.com/repos/SIMPLE-BuildingSimulation/heat/pulls/20.
✔ Successfully opened pull request: 20.
✔ Successfully added labels autorelease: pending to issue: 20
```
