### ISSUE TITLE
Using release-please without releases

### ISSUE THREAD

**Issue by blahxer** [google-github-actions/release-please-action#660]
Is it possible to use release-please without doing github releases? I have done some attempts, but if I use skip-github-release: true it will not update the version and tag the commit. And using release type simple zips up the whole repo. 

My use case is: I want to use release-please purely for semver, conventional commits and changelog. The actual building and deployment of builds I want to manage in a separate step since it is not supported by release-please.

Not sure if I am just missing something obvious :) 

Thank you!

**Comment by ddennis** [comment]
Sorry if i am mis-understanding. I am also new to release-please.
You dont have to do anything with the github release. 
You can just detect if a release was made, When a release is made the semver is updated.

````
jobs:
  release-please:
    runs-on: ubuntu-latest

    outputs:
      buildFlag: ${{ steps.validate.outputs.build }}

    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: release-please-action
         
      - name: release output
        run: echo '${{ toJSON(steps) }}'

        # based on the output from release plase
      - name: check for new release
        id: validate
        run: |
          if [ ${{steps.release.outputs.release_created}} == "true" ]; then
            echo "build=BUILD" >> $GITHUB_OUTPUT
          else
            echo "build=DISCARD" >> $GITHUB_OUTPUT
          fi

      - name: saved outputs
        run: echo '${{ toJSON(steps.validate)}}'

 # your own deployment job
  output-test:
    runs-on: ubuntu-latest
    needs: release-please
    steps:
      - name: next task
        run: echo '${{ toJSON(needs.release-please) }}'

        #run what ever task you need - if a new release was made
      - name: should it build
        if: ${{needs.release-please.outputs.buildFlag == 'BUILD' }}
        run: echo ${{needs.release-please.outputs.buildFlag }}

      - name: is it discard
        if: ${{needs.release-please.outputs.buildFlag == 'DISCARD' }}
        run: echo ${{needs.release-please.outputs.buildFlag }}


````
