### ISSUE TITLE
Is there a way prevent a release being labelled as latest?

### ISSUE THREAD

**Issue by simonmcallister0210** [google-github-actions/release-please-action#678]
At the moment, if a merge a release PR for a backport version (1.x.x), the new release gets labelled as "latest" by github, even though I have a later version (2.x.x)

incase you need it, here's my workflow files for main/2.x.x and 1.x.x:

```yml
name: release
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          default-branch: main
```

```yml
name: release
on:
  push:
    branches:
      - 1.x.x
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          default-branch: 1.x.x
```
