### ISSUE TITLE
URLs are not working when a PR gets created

### ISSUE THREAD

**Issue by paulfouquet** [google-github-actions/release-please-action#693]
### TL;DR

When a new release PR is created, the message the PR/commits URL in the following messages in the GitHub Actions logs for 
`Run google-github-actions/release-please-action@v3` seem wrong: `Successfully opened pull request available at url: https://api.github.com/repos/[ORG]/[REPO]/pulls/29.` / `Successfully created commit. See commit at https://api.github.com/repos/[ORG]/[REPO]/git/commits/[COMMIT]`

### Expected behavior

The URLs should not contains `api.`

### Action YAML

```yaml
on:
  push:
    branches:
      - master

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: python
          token: ${{ secrets.GITHUB_TOKEN }}

  publish-release:
    needs: release-please
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - uses: ./.github/workflows/containers
```
