### ISSUE TITLE
Release PR is not getting created

### ISSUE THREAD

**Issue by d1onys1us** [google-github-actions/release-please-action#698]
### TL;DR

The release PR is not being created after one commit has been merged (after the latest release PR was merged). I am seeing ✔ No user facing commits found since 27691e6713810d2fc3923fd1704116c11dffed05 - skipping

### Action YAML

```yaml
on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
```

### Log output

```
✔ Building candidate release pull request for path: packages/website
❯ type: node
❯ targetBranch: main
❯ commits: 1
✔ Considering: 1 commits
❯ component: website
❯ pull request title pattern: undefined
✔ No user facing commits found since 27691e6713810d2fc3923fd1704116c11dffed05 - skipping
```

### Additional information

the failing action is here (the repo is open source): https://github.com/taikoxyz/taiko-mono/actions/runs/3955630714/jobs/6774080262
