### ISSUE TITLE
'No commits for path: ., skipping' when merging a Release PR

### ISSUE THREAD

**Issue by matteoredz** [google-github-actions/release-please-action#699]
### TL;DR

The Release PR gets appropriately created but when I merge it the GitHub Release gets created but `release_created` is not emitted.

### Expected behavior

I'd expect that if the Release PR contains the right commit list when it gets merged the `release_created` output is emitted.

### Observed behavior

The release gets skipped

### Action YAML

```yaml
name: Release

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"refactor","section":"Refactoring","hidden":false},{"type":"docs","section":"Documentation","hidden":false},{"type":"test","section":"Test","hidden":false}]'
          package-name: rack-idempotency_key
          release-type: ruby
          token: ${{secrets.GITHUB_TOKEN}}
          version-file: "lib/rack/idempotency_key/version.rb"
      - uses: actions/checkout@v3
        if: ${{steps.release.outputs.release_created}}
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 2.7.0
        if: ${{steps.release.outputs.release_created}}
      - run: bundle install
        if: ${{steps.release.outputs.release_created}}
      - run: ./bin/release
        env:
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
        if: ${{steps.release.outputs.release_created}}
```

### Log output

```text
Run google-github-actions/release-please-action@v3
✔ Looking for latest release on branch: main with prefix: rack-idempotency_key
❯ Fetching merge commits on branch main with cursor: undefined
❯ Found latest release pull request: 21 version: 0.2.0
❯ Fetching releases with cursor undefined
❯ found release for rack-idempotency_key Version {
  major: 0,
  minor: 1,
  patch: 0,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found 1 possible releases. [
  Version {
    major: 0,
    minor: 2,
    patch: 0,
    preRelease: undefined,
    build: undefined
  }
]
✔ Building releases
✔ Building strategies by path
❯ .: ruby
❯ Found pull request #21: 'chore(main): release 0.2.0'
✔ Building release for path: .
❯ type: ruby
❯ targetBranch: main
✔ Creating 1 releases for pull #21
❯ adding comment to https://github.com/matteoredz/rack-idempotency_key/issue/21
❯ removing labels: autorelease: pending from issue/pull 21
❯ adding labels: autorelease: tagged from issue/pull 21
✔ Looking for latest release on branch: main with prefix: rack-idempotency_key
❯ Fetching merge commits on branch main with cursor: undefined
❯ Found latest release pull request: 21 version: 0.2.0
❯ Fetching releases with cursor undefined
❯ found release for rack-idempotency_key Version {
  major: 0,
  minor: 2,
  patch: 0,
  preRelease: undefined,
  build: undefined
}
❯ found release for rack-idempotency_key Version {
  major: 0,
  minor: 1,
  patch: 0,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found 2 possible releases. [
  Version {
    major: 0,
    minor: 2,
    patch: 0,
    preRelease: undefined,
    build: undefined
  },
  Version {
    major: 0,
    minor: 2,
    patch: 0,
    preRelease: undefined,
    build: undefined
  }
]
✔ Building pull requests
✔ Building strategies by path
❯ .: ruby
✔ Collecting release commit SHAs
❯ release search depth: 400
❯ Fetching releases with cursor undefined
❯ Found release for path ., v0.2.0
❯ release for path: ., version: 0.2.0, sha: b0640f85189591c0c2d84bf23cd2fecf2420becc
✔ Collecting commits since all latest releases
❯ commit search depth: 500
❯ Set(1) { 'b0640f85189591c0c2d84bf23cd2fecf2420becc' }
❯ Fetching merge commits on branch main with cursor: undefined
❯ Backfilling file list for commit: 157df4045ea66b0115674dc06ba4f67d3bfbf3b8
❯ Found 5 files
❯ Backfilling file list for commit: 102e66d3d2bb14f9ac54a251e02d631e1d97c179
❯ Found 8 files
❯ Backfilling file list for commit: a9f0eed9f64750b73690581484f21b897d9755e9
❯ Found 3 files
❯ Backfilling file list for commit: 3e0fe900470fd82600855238577c087037ff525c
❯ Found 2 files
❯ Backfilling file list for commit: 6ef58ba65e8f0bb3801e7a7fa25e8375429ad8af
❯ Found 1 files
❯ Backfilling file list for commit: d02dbdbb64bcf98b6b4c68d1965471ddc561fa9d
❯ Found 22 files
✔ Splitting 0 commits by path
✔ Building candidate release pull request for path: .
❯ type: ruby
❯ targetBranch: main
❯ commits: 0
✔ Considering: 0 commits
✔ No commits for path: ., skipping
```
