### ISSUE TITLE
Add a configuration to use another github user for PR creation as the github actions bot

### ISSUE THREAD

**Issue by flovogt** [google-github-actions/release-please-action#700]
### TL;DR

I wanna use release-please but the release PRs should be created by another user than the github actions bot.

I tried
````yml

on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        env:
          GIT_AUTHOR_NAME: "My Bot"
          GIT_AUTHOR_EMAIL: "my...@.com"
          GIT_COMMITTER_NAME: "My Bot"
          GIT_COMMITTER_EMAIL: "my...@.com"
        with:
          command: manifest
````

But the commit is still done by the gh actions bot.

**Comment by flovogt** [comment]
Got it working by providing an own secret which was generated by the desired user.

````yml

on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          token: ${{secrets.MY_TOKEN}}
````
