### ISSUE TITLE
Unable to configure release please to the project

### ISSUE THREAD

**Issue by lopapex** [google-github-actions/release-please-action#701]
### TL;DR

After creating this job I am unable to make it work. Does anyone have a Idea what do I do wrong?

[release-please](https://github.com/skaut/kapesni_skautis/actions/runs/3975060913/jobs/6814754452#step:2:515)
release-please failed: Error updating ref heads/release-please--branches--master--components--release-please-action to 27f4a96df246ad24ba0eda1c7ad5524ed4395a71
![image](https://user-images.githubusercontent.com/61870540/213871336-efb9277b-aa63-457c-9faf-b8fcbcc670a8.png)

### Action YAML

```yaml
on:
  push:
    branches: [master]

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
```
