### ISSUE TITLE
`release-as` in action input should work when using the `manifest` command

### ISSUE THREAD

**Issue by damienwebdev** [google-github-actions/release-please-action#715]
### TL;DR

I was trying to pre-release a package that I maintain with `release-please`.

I wanted to use ` workflow_dispatch` so that if I manually trigger the workflow, it will create a pre-release PR with a customized semver-compliant alpha version. However, so long as I use the `manifest` command in the action, my `release-as` input is ignored.

My workflow looked like:

```yml
name: Create Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      releaseAs:
        description: Release tag to be used (e.g. 0.1.1-alpha)
        required: true


jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
         if: github.event_name == 'workflow_dispatch'
         with:
           token: ${{ secrets.SOME_TOKEN }}
           command: manifest
           release-as: ${{ github.events.inputs.releaseAs }}
           default-branch: main

      - uses: google-github-actions/release-please-action@v3
         with: github.event_name != 'workflow_dispatch'
           token: ${{ secrets.SOME_TOKEN }}
           command: manifest
           default-branch: main
```

### Detailed design

It's probably most sustainable to merge action inputs OVER the config in the event the action input is defined.
