### ISSUE TITLE
prerelease is ignored

### ISSUE THREAD

**Issue by DuncanCasteleyn** [google-github-actions/release-please-action#721]
### TL;DR

I have prerelease set to true, but my release does not get marked as pre-release

### Expected behavior

I expected a pre-release to be created.

### Observed behavior

I got a release that was not marked as pre-release.

### Action YAML

```yaml
- uses: google-github-actions/release-please-action@d3c71f9a0a55385580de793de58da057b3560862 # v3
        id: release
        with:
          release-type: maven
          prerelease: true
```
