### ISSUE TITLE
Documentation doesn't outline permission flags required

### ISSUE THREAD

**Issue by airtonix** [google-github-actions/release-please-action#724]
### TL;DR

[This section](https://github.com/google-github-actions/release-please-action#github-credentials) is about as close as it gets to talking about this topic (but still neglects to talk about permission flags): 

> GitHub credentials
> release-please requires a GitHub token to access the GitHub API. You configure this token via the token configuration option. You can use the built-in GITHUB_TOKEN secret, however, note that any resources created by release-please (release tag or release pull request) will not trigger future GitHub actions workflows.
> 
> From the [docs](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow):
> 
> When you use the repository's GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN will not create a new workflow run. This prevents you from accidentally creating recursive workflow runs.
> 
> This means that GitHub actions CI checks will not run on the release pull request and workflows normally triggered by release.created events will also not run. You will want to configure a GitHub actions secret with a [personal access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) if you want other workflows to run.

### Expected behavior

We should list the permission flags required so that workflow files can describe the exact flags: 

```
name: Release

on:
  push:
    branches:
      - main

jobs:
  release-please:

    runs-on: ubuntu-latest
    
    # which ones are required ??
    permissions:
      actions: read|write|none
      checks: read|write|none
      contents: read|write|none
      deployments: read|write|none
      id-token: read|write|none
      issues: read|write|none
      discussions: read|write|none
      packages: read|write|none
      pages: read|write|none
      pull-requests: read|write|none
      repository-projects: read|write|none
      security-events: read|write|none
      statuses: read|write|none

    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        with:
          release-type: simple

```

### Observed behavior

documentation doesn't outline exactly what permissions are required.

### Action YAML

```yaml
name: Release

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        with:
          release-type: simple
```
