### ISSUE TITLE
How can i use "bump version"

### ISSUE THREAD

**Issue by denis-ottofeller** [google-github-actions/release-please-action#726]
### TL;DR

I want to use the manual trigger for workflow with one input "Release Type", which includes 3 options "patch", "minor", and "major". How i can use this input for bump version?

### Detailed design

```yml
name: New release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Release Type'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
```
