### ISSUE TITLE
replease PR are not creating

### ISSUE THREAD

**Issue by venkateshthalanki** [google-github-actions/release-please-action#736]
### TL;DR

When developer updates his branch with master. Github is giving standard commit message(Merge branch 'master' into bug-141639-featurebranch)

Action is not able to parse the message and PR is not getting created.

### Action YAML

```yaml
steps:
      - name: Create Release 🚀
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
```

### Log output

```text
commit could not be parsed: f9a54b467c8267e456dcd46a651c66cb217ca0fd Merge pull request #193 from philips-internal/bug-141639-edit-session-revoke-when-call-end
❯ commit could not be parsed: 4fb31fb112f33d87bd4d309e1cba5263da8cde40 Merge branch 'master' into bug-141639-edit-session-revoke-when-call-end
```

**Comment by Tragio** [comment]
I'm also having this error. I'm pushing to master and I want it to create a PR against release branch.

I already did several commits `fix: something`, `fix!: something` and `chore: something`, and no PR was created.

```yml
on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: app
          default-branch: release
```

```
✔ Building candidate release pull request for path: .
❯ type: node
❯ targetBranch: release
❯ commit could not be parsed: 29faba68b8adbb96035a0b80fa68c9fe5384f18a Merge pull request #380 from Tragio/master
⚠ No latest release pull request found.
❯ commits: 0
✔ Considering: 0 commits
✔ No commits for path: ., skipping
```

**Comment by venkateshthalanki** [comment]
Team, any update on this bug

**Comment by csellis** [comment]
Experiencing this one as well with PR to `main`.

```
name: Release

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

env:
  PUBLIC_NODE_ENV: 'ci'
  # The following are required for semantic-release to build. They are not used for production.
  DATABASE_URL: ${{ secrets.PLAYWRIGHT_TEST_DB_STAGING }}
  PRIVATE_FACEBOOK_CAPI_TOKEN: ''

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release-please
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: release-please-action
```

```
✔ Building pull requests
✔ Building strategies by path
❯ .: node
✔ Collecting release commit SHAs
❯ release search depth: 400
❯ Fetching releases with cursor undefined
❯ Found release for path ., v1.0.0
❯ release for path: ., version: 1.0.0, sha: 1f5f1696b21a4bc627a3409defef923c76c090fa
✔ Collecting commits since all latest releases
❯ commit search depth: 500
❯ Set(1) { '1f5f1696b21a4bc627a3409defef923c76c090fa' }
❯ Fetching merge commits on branch main with cursor: undefined
❯ Backfilling file list for commit: 669a5f9688a9f54692c7b3c1a4739[81](https://github.com/xtendops-developers/apply-sveltekit/actions/runs/4532101626/jobs/7983063931#step:2:82)72292dee1
❯ Found 0 files
❯ Backfilling file list for commit: ed3b044b1e0102fe09ecb852dc0022da17a6d4f7
❯ Found 2 files
✔ Splitting 1 commits by path
✔ Building candidate release pull request for path: .
❯ type: node
❯ targetBranch: main
❯ commit could not be parsed: 0672429572b3e8f5adcb7b7bb[83](https://github.com/xtendops-developers/apply-sveltekit/actions/runs/4532101626/jobs/7983063931#step:2:84)9e375487d0b03 Cu [86](https://github.com/xtendops-developers/apply-sveltekit/actions/runs/4532101626/jobs/7983063931#step:2:87)77gztw7 prevent retaking assessments daniel espinosa (#311)
❯ commits: 0
✔ Considering: 0 commits
✔ No commits for path: ., skipping
```
