### ISSUE TITLE
"changelog-notes-type: github" doesn't work properly

### ISSUE THREAD

**Issue by OleksandrKrupko** [google-github-actions/release-please-action#744]
### TL;DR

When I set "changelog-notes-type: github" & the release PR is merged - generated GitHub release message is empty - it just shows the release PR merge commit content with raw formatting

I really do like the GitHub notes strategy because it uses pull request titles for the change line, not every commit from every merged pull request, like the default strategy. But because of these issues, I cannot really use it

What I really want is for my changelogs to have messages from the merged pull requests, not every commit. Because a PR can have 10 commit messages that all start from feat(ticket-id), and I don't want all of them to show up in the changelog, only a single line. If there is a way to do it without using the GitHub notes strategy, I'd be thankful for the suggestion, or otherwise how I can make the GitHub strategy work as I believe it's expected (p.s.: squash commits on merge is also not an option for us, as it results in unnecessary code conflicts)

### Expected behavior

- Generated GitHub release has a message, it's not empty. Right now it just has a commit message, but it doesn't use any formatting. (Because I use "Use commit message for merge commits" option - it actually shows something, but without any formatting)
![image](https://user-images.githubusercontent.com/47849720/227595769-9ed8f469-4f25-4f12-ac75-5918b6cd4223.png)

### Action YAML

```yaml
- uses: google-github-actions/release-please-action@v3
      id: release
      with:
        release-type: node
        changelog-notes-type: github
        package-name: release-please-action
        # we use a custom versions approach and set this variable, but this shouldn't matter I believe, it's a usual semver version - like 0.45.3
        release-as: ${{ env.NEXT_MINOR_VERSION }}
```
