### ISSUE TITLE
Failure in release please PR creation

### ISSUE THREAD

**Issue by venkateshthalanki** [google-github-actions/release-please-action#745]
### TL;DR

When developer updates his branch with master. Github is giving standard commit message(Merge branch 'master' into bug-141639-featurebranch)

Action is not able to parse the message and PR is not getting created.

Extension of #736 

### Action YAML

```yaml
steps:
      - name: Create Release 🚀
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
```

### Log output

```text
commit could not be parsed: f9a54b467c8267e456dcd46a651c66cb217ca0fd Merge pull request #193 from philips-internal/bug-141639-edit-session-revoke-when-call-end
❯ commit could not be parsed: 4fb31fb112f33d87bd4d309e1cba5263da8cde40 Merge branch 'master' into bug-141639-edit-session-revoke-when-call-end
```

### Additional information

extension of #736
