### ISSUE TITLE
Please provide an option to skip Pr creation

### ISSUE THREAD

**Issue by cakeinpanic** [google-github-actions/release-please-action#748]
### TL;DR

Hi, I love this action, but sometimes I don't want automatic PR to be generated, I just want to get recommended version bump + changelog to add and handle them myself

### Detailed design

Suggested API looks like this
```

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release 
        with:
          release-type: node
          package-name: release-please-action
          skip-pr-creation: true

     - run: |
          echo  "${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}"
          echo "changelog: ${{ steps.release.outputs.changelog }}"
```
