### ISSUE TITLE
`snapshot-labels` option appears not to work

### ISSUE THREAD

**Issue by matJC** [google-github-actions/release-please-action#749]
### TL;DR

Having added `snapshot-labels: automerge` to my release-please step configuration, I'm not seeing the label applied to the release PR.

### Expected behavior

I'd expect the label to be applied to snapshot bump release PRs under the java release type.

### Observed behavior

The `autorelease: snapshot` label is added, but not the configured `automerge` label.

### Action YAML

```yaml
name: release-please

on:
  workflow_call:
    inputs:
      branch:
        description: "the branch release please will check for new conventional commits"
        type: string
        default: main
    outputs:
      release_created:
        description: "true if the release was created, false otherwise"
        value: ${{ jobs.release-please.outputs.release_created }}
      package_version:
        description: "the new semantic version"
        value: ${{ jobs.release-please.outputs.version }}

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      version: ${{ steps.release-please.outputs.version }}
    steps:
      - id: 'release-please'
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          default-branch: ${{ inputs.branch }}
          snapshot-labels: automerge
```

### Log output

```text
Run google-github-actions/release-please-action@v3
  with:
    command: manifest
    default-branch: main
    snapshot-labels: automerge
    token: ***
    fork: false
    clean: true
    bump-minor-pre-major: false
    bump-patch-for-minor-pre-major: false
    changelog-host: https://github.com
    github-api-url: https://api.github.com
    github-graphql-url: https://api.github.com/graphql
    monorepo-tags: false
❯ Fetching release-please-config.json from branch main
❯ Fetching .release-please-manifest.json from branch main
✔ Building pull requests
✔ Building strategies by path
❯ .: java
✔ Collecting release commit SHAs
❯ release search depth: 400
❯ Fetching releases with cursor undefined
❯ Found release for path ., v0.0.5
❯ release for path: ., version: 0.0.5, sha: e03b60b9205e11d5d2eb3f1f6f7a504f6de2c8ed
✔ Collecting commits since all latest releases
❯ commit search depth: 500
❯ Set(1) { 'e03b60b9205e11d5d2eb3f1f6f7a504f6de2c8ed' }
❯ Fetching merge commits on branch main with cursor: undefined
❯ Backfilling file list for commit: 5ec4772847e40c6e43f0b257103e6656aac9e7c7
❯ Found 3 files
❯ Backfilling file list for commit: df5d0155c16693d40408bacb01af43c65130b9ba
❯ Found 0 files
❯ Backfilling file list for commit: 3931038e7eba04c4d707d326a7f80db4cda5b419
❯ Found 1 files
❯ Backfilling file list for commit: a5609ae4a3a0abd605953fcde6f054b1d639877c
❯ Found 1 files
❯ Backfilling file list for commit: 4b21c2ffb603021b5c9fc3063a35cdb69aade928
❯ Found 1 files
❯ Backfilling file list for commit: f9fbc8273acc9a6ae52a4ee77d91c889f11d06c2
❯ Found 1 files
❯ Backfilling file list for commit: d7fbce7559601f4399de4d333d181c3c1738ac42
❯ Found 3 files
❯ Backfilling file list for commit: b43910a6932b546cc0e687a8b5ca608818650ce0
❯ Found 1 files
❯ Backfilling file list for commit: 071c6d57aba63be32c33dcb39a732f637bc5d3a1
❯ Found 1 files
❯ Backfilling file list for commit: 6e2fa08c3338a07d70e687697b4f58977bbc4df4
❯ Found 0 files
❯ Backfilling file list for commit: d243daaf63e0085a55fd7f629ae4071a54628986
❯ Found 1 files
❯ Backfilling file list for commit: fffd69b7a78e8bc80ee28e9bd40579ccf37ac5ba
❯ Found 3 files
❯ Backfilling file list for commit: b9d7db19a29ec46e6f04c94958b07fe8261ecaf7
❯ Found 0 files
❯ Backfilling file list for commit: 8a95871471fd539b975c5523a938a04cf9d9eec9
❯ Found 1 files
❯ Backfilling file list for commit: 7c17a14e8dbe09d24f63d362505b645d3ae7540c
❯ Found 1 files
❯ Backfilling file list for commit: 2c2ab76c238a49826dedf7c09768952036fbbce3
❯ Found 1 files
❯ Backfilling file list for commit: 21c895ae51ca933ce3c23db622e9f4c8dd0761ec
❯ Found 3 files
❯ Backfilling file list for commit: 356da07f689aa66b243e9232c77db8556a832f62
❯ Found 3 files
✔ Splitting 0 commits by path
✔ Building candidate release pull request for path: .
❯ type: java
❯ targetBranch: main
❯ commits: 0
❯ component: 
✔ Repository needs a snapshot bump.
✔ Looking for open release pull requests
✔ found 0 open release pull requests.
✔ Looking for snoozed release pull requests
✔ found 0 snoozed release pull requests.
❯ Fetching gradle.properties from branch main
❯ Fetching src/main/resources/openapi.yml from branch main
⚠ file src/main/resources/openapi.yml did not exist
✔ Starting GitHub PR workflow...
✔ Successfully found branch HEAD sha "e03b60b9205e11d5d2eb3f1f6f7a504f6de2c8ed".
✔ Successfully created branch at https://api.github.com/repos/example/repository/git/refs/heads/release-please--branches--main
✔ Got the latest commit tree
✔ Successfully created a tree with the desired changes with SHA 76ed98ee6bc33c2e50b57fd46a2a54e44672ba34
✔ Successfully created commit. See commit at https://api.github.com/repos/exampl/repository/git/commits/314de603abc5a7587dcb722bec67a317f075208b
✔ Updating reference heads/release-please--branches--main to 314de603abc5a7587dcb722bec67a317f075208b
✔ Successfully updated reference release-please--branches--main to 314de603abc5a7587dcb722bec67a317f075208b
✔ Successfully opened pull request available at url: https://api.github.com/repos/example/repository/pulls/9.
✔ Successfully opened pull request: 9.
✔ Successfully added labels autorelease: snapshot to issue: 9
❯ Fetching release-please-config.json from branch main
❯ Fetching .release-please-manifest.json from branch main
✔ Building releases
✔ Building strategies by path
❯ .: java
```

### Additional information

Note that I've created the label itself in my repo, so it can be added manually if one were to choose to do so.

Notice operatively in the log:
```
Run google-github-actions/release-please-action@v3
  with:
    ...
    snapshot-labels: automerge
```

```
✔ Repository needs a snapshot bump.
```

```
✔ Successfully added labels autorelease: snapshot to issue: 9
```
