### ISSUE TITLE
Please provide an option to define a custom branch name for the pull request created by the action

### ISSUE THREAD

**Issue by faelfael1498** [google-github-actions/release-please-action#766]
### TL;DR

Hi, would be great to provide the possibility to pass custom branch name for the automatic pull request that is opened by the action. When having specifc branch naming hooks enabled on a repo the workflow fails as its not conform with the allowed branch naming. The pull request creation will be rejected by the hook.

### Detailed design

Could be an additional configuration input parameter like for example -> pr-branch-name

```
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release 
        with:
          release-type: node
          package-name: release-please-action
          pr-branch-name: ${{ custom_branch_name }}
```
