### ISSUE TITLE
Error: release-please failed: GitHub Actions is not permitted to create or approve pull requests

### ISSUE THREAD

**Issue by tekumara** [google-github-actions/release-please-action#767]
### TL;DR

Error: release-please failed: GitHub Actions is not permitted to create or approve pull requests

### Action YAML

```yaml
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: typos-vscode
```

### Log output

```text
✔ Starting GitHub PR workflow...
✔ Successfully found branch HEAD sha "bd5d4ea88c70e234e34e9b97e4401258424f6c62".
✔ Successfully created branch at https://api.github.com/repos/tekumara/typos-vscode/git/refs/heads/release-please--branches--main--components--typos-vscode
✔ Got the latest commit tree
✔ Successfully created a tree with the desired changes with SHA 6dc6d70058023d0000a675c9f53e1b34f574ce4f
✔ Successfully created commit. See commit at https://api.github.com/repos/tekumara/typos-vscode/git/commits/de21fa40fc9eb21569ec85358b4abda8153f7ad6
✔ Updating reference heads/release-please--branches--main--components--typos-vscode to de21fa40fc9eb21569ec85358b4abda8153f7ad6
✔ Successfully updated reference release-please--branches--main--components--typos-vscode to de21fa40fc9eb21569ec85358b4abda8153f7ad6
Error: release-please failed: GitHub Actions is not permitted to create or approve pull requests.
```

### Additional information

See https://github.com/tekumara/typos-vscode/actions/runs/4842582398/jobs/8629626808#step:2:235

**Comment by tekumara** [comment]
To resolve, on the repo settings make sure "Allow GitHub Actions to create and approve pull requests" is checked:

 
<img width="661" alt="CleanShot 2023-04-30 at 15 08 19@2x" src="https://user-images.githubusercontent.com/125105/235336703-5ac39b51-0e60-41d7-83a9-70e8ea5f5bef.png">

Perhaps this could be added to the readme?

**Comment by kettanaito** [comment]
Can this be configured on the workflow level in the `permissions` field?

```yml
// .github/workflows/release.yml
permissions:
  contents: write
  pull-requests: write
```

Those should propagate to the `GITHUB_TOKEN` secret set by GitHub Actions.

If not, I suppose you should create a scoped PAT that allows those permissions and provide it as the `token` argument to the release please action.
