### ISSUE TITLE
gradle file not updated by extra-files

### ISSUE THREAD

**Issue by MartinWitt** [google-github-actions/release-please-action#773]
### TL;DR

build.gradle file not update with extrafile option in the github-action.

### Expected behavior

I expect the version in https://github.com/MartinWitt/laughing-train/blob/master/buildSrc/src/main/groovy/xyz.keksdose.spoon.code_solver.java-common-conventions.gradle#L90 to be update to new one.

### Observed behavior

The version is not updated in the PR https://github.com/MartinWitt/laughing-train/pull/652

### Action YAML

```yaml
on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: java
          package-name: release-please-action
          extra-files: |
              buildSrc/src/main/groovy/xyz.keksdose.spoon.code_solver.java-common-conventions.gradle
```

### Log output

```text
https://github.com/MartinWitt/laughing-train/actions/runs/4996484781/jobs/8949915401
```
