### ISSUE TITLE
Javascript error v3.7.10

### ISSUE THREAD

**Issue by kaiivoschneider** [google-github-actions/release-please-action#786]
### TL;DR

After updating the action to v3.7.10 I am getting a javascript error during my release run. Switching back to v3.7.9 fixes this issue.

### Action YAML

```yaml
release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: google-github-actions/release-please-action
          path: .github/actions/release-please-action
          ref: v3.7.10
      - uses: ./.github/actions/release-please-action
        id: release
        with:
          command: manifest
          default-branch: ${{ github.ref_name }}
```

### Log output

```text
...
✔ appending dependency notes to changelog
✔ appending dependency notes to changelog
✔ Post-processing 2 in-scope candidates
❯ running plugin: LinkedVersions
✔ found 2 linked-versions candidates
Error: release-please failed: Cannot read properties of undefined (reading 'replace')
```
