### ISSUE TITLE
Not able to use non-relative paths in extra-paths

### ISSUE THREAD

**Issue by 1aziz** [google-github-actions/release-please-action#789]
### TL;DR

 When using `path` in my workflow to update a Helm chart version, I can't use `extra-paths` to also update the same version referenced in another path, because all paths used in  is relative to path used in `path`. 

### Expected behavior

The paths used in `extra-paths` should probably not be relative. I should be able to update the version in another "package". 

### Action YAML

```yaml
name: release chartA

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          path: packages/chartA
          release-type: helm
          package-name: chartA
          monorepo-tags: true
          tag-separator: "@"
          pull-request-title-pattern: "chore(${component}): release chart version ${version}"
          pull-request-header: "🚀 New Helm chart release."
          extra-files: |
           ../gitops/template.yaml
```
