### ISSUE TITLE
include-component-in-tag is ignored by action

### ISSUE THREAD

**Issue by gavinbarron** [google-github-actions/release-please-action#796]
`### TL;DR

I have a release-please.config.json with `include-component-in-tag: false` this setting seems to be ignored by the CI action I have configured.

When testing with the CLI I saw that the `include-component-in-tag` setting was correctly being used.

### Expected behavior

Diff links to use tags in the form of `v{{SemVer}}`

### Observed behavior

dif links use tags with a component name of root despite configuration: https://github.com/microsoftgraph/microsoft-graph-toolkit/pull/2611/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR5

### Action YAML

```yaml
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write

name: Run Release Please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
      - uses: google-github-actions/release-please-action@v2
        id: release
        with:
          command: manifest
          token: ${{secrets.RELEASE_PLEASE_TOKEN}}
          default-branch: main
```

### Log output

```text
https://github.com/microsoftgraph/microsoft-graph-toolkit/actions/runs/5582290651/jobs/10201416239
```

### Additional information

[.release-please-manifest.json](https://github.com/microsoftgraph/microsoft-graph-toolkit/blob/main/.release-please-manifest.json)
[release-please-config.json](https://github.com/microsoftgraph/microsoft-graph-toolkit/blob/main/release-please-config.json)
