### ISSUE TITLE
The `extra-files` doesn't seem to be working.

### ISSUE THREAD

**Issue by YanceyOfficial** [google-github-actions/release-please-action#802]
### TL;DR

I have a [tauri app](https://github.com/HyperChatBot/hyperchat). My idea was that when the version number in `package.json `updates, the version numbers in `src-tauri/Cargo.toml` and `src-tauri/tauri.conf.json` should also update. However, in fact, they did not update. Could you please take a look and see if my configuration is incorrect?

### Action YAML

```yaml
on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
          extra-files: |
            src-tauri/Cargo.toml
            src-tauri/tauri.conf.json
```
