### ISSUE TITLE
Commits with scope "deps" does not trigger the creation of a release pr

### ISSUE THREAD

**Issue by flovogt** [google-github-actions/release-please-action#804]
### TL;DR

Commits with scope "deps" does not trigger the creation of a release pr.

### Expected behavior

My assumption is that a commit (e.g. https://github.com/SAP/ui5-tooling-extensions/commit/bd5a78abaf0cf8a1218db9b2e076442398e4c184) with commit message `deps: bump packageX to version Y` will create a release PR.

### Observed behavior

No release PR is created.

### Action YAML

```yaml
on:
  workflow_dispatch:
    inputs:
      new-version:
        description: 'The semver version of the new release'
        required: true
        type: string
      package-folder:
        description: 'The package to be released'
        required: true
        type: choice
        options:
          - middleware-code-coverage
  push:
    branches:
      - main
name: release-please
jobs:
  pull-request:
    runs-on: ubuntu-22.04
    outputs:
      releases_created: ${{steps.release.outputs.releases_created}}
      paths_released: ${{steps.release.outputs.paths_released}}
    steps:
    - uses: google-github-actions/release-please-action@v3
      id: release
      with:
        command: manifest
        token: ${{secrets.GH_OPENUI5BOT}}
        monorepo-tags: true
        release-as: ${{ inputs.new-version }}
        path: packages/${{ inputs.package-folder }}
  publish-package:
    needs: pull-request
    if: ${{needs.pull-request.outputs.releases_created}}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        path_released: ${{fromJson(needs.pull-request.outputs.paths_released)}}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Use Node.js LTS 18.x
      uses: actions/setup-node@v3.6.0
      with:
        node-version: 18.x
    - name: Publish to NPM
      env:
        NPM_TOKEN: ${{secrets.NPM_UI5BOT}}
      run: |
        cd ${{ matrix.path_released }}
        echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> ./.npmrc
        npm publish --workspaces false --access public
```

### Log output

```text
❯ Fetching release-please-config.json from branch main
❯ Fetching .release-please-manifest.json from branch main
✔ Building releases
✔ Building strategies by path
❯ packages/middleware-code-coverage: node
❯ Fetching release-please-config.json from branch main
❯ Fetching .release-please-manifest.json from branch main
✔ Building pull requests
✔ Building strategies by path
❯ packages/middleware-code-coverage: node
❯ Fetching packages/middleware-code-coverage/package.json from branch main
✔ Collecting release commit SHAs
❯ release search depth: 400
❯ Fetching releases with cursor undefined
❯ Found release for path packages/middleware-code-coverage, middleware-code-coverage-v1.0.3
❯ release for path: packages/middleware-code-coverage, version: 1.0.3, sha: 640fdc8faec728337cea56ec1c05ad16478b29d5
✔ Collecting commits since all latest releases
❯ commit search depth: 500
❯ Set(1) { '640fdc8faec728337cea56ec1c05ad16478b29d5' }
❯ Fetching merge commits on branch main with cursor: undefined
❯ Backfilling file list for commit: 28d4026a883d60b53b6eacd3f5976f79a1819e3d
❯ Found 1 files
❯ Fetching merge commits on branch main with cursor: bd5a78abaf0cf8a1218db9b2e076442398e4c184 24
❯ Fetching merge commits on branch main with cursor: bd5a78abaf0cf8a1218db9b2e076442398e4c184 49
❯ Backfilling file list for commit: e59e921780ace11cdf2bc1ff98e2af241580f118
❯ Found 1 files
✔ Splitting 51 commits by path
✔ Building candidate release pull request for path: packages/middleware-code-coverage
❯ type: node
❯ targetBranch: main
❯ commits: 56
✔ Considering: 56 commits
❯ component: middleware-code-coverage
❯ pull request title pattern: release:${component} v${version}
⚠ pullRequestTitlePattern miss the part of '${scope}'
✔ No user facing commits found since 640fdc8faec728337cea56ec1c05ad16478b29d5 - skipping
```

### Additional information

Its a mono-repo and the lockfile is only stored on the root level of the repository. The subpackage does not have its own lockfile.
