### ISSUE TITLE
Unable to create releases from another branch than the default branch

### ISSUE THREAD

**Issue by realmunk** [google-github-actions/release-please-action#806]
### TL;DR

I am unable to create releases when setting the default-branch manually.

### Expected behavior

Be able to cut a release branch (1.x) and get new release PR's for this branch when cherry-picking in new commits.

### Observed behavior

The action fails.

### Action YAML

```yaml
name: 'Publish new release PR'

on:
  push:
    branches:
      - '**.x'

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    if: "!contains(github.event.head_commit.message, 'chore: release ')"
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        id: extract-branch
        uses: actions/github-script@v6
        with:
          script: |
            // Get the reference from the context
            const ref = context.ref;

            // Extract the branch name from the reference
            const branchName = ref.replace('refs/heads/', '');

            // Set the branch name as an output variable
            return branchName;
      - uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          token: ${{ secrets.SYSTEM_BOT }}
          default-branch: ${{ steps.extract-branch.outputs.result }}
```

### Log output

```text
Run google-github-actions/release-please-action@v3
❯ Fetching release-please-config.json from branch "1.x"
❯ Fetching .release-please-manifest.json from branch "1.x"
Error: release-please failed: base (schibsted-smb/playground-test): Missing required manifest versions: .release-please-manifest.json
```

### Additional information

I have tried with several different patterns with no luck. However, if I updated the ref to include `refs/heads` then it was able to check out the code – however that produced a different error:
```
✔ Successfully created a tree with the desired changes with SHA 2be41878a33311c87af171cd52c1a8383bd32b2f
✔ Successfully created commit. See commit at https://api.github.com/repos/[sensored]/git/commits/460964618e9c78456db66667b8503c2de2499874
✔ Updating reference heads/release-please--branches--refs/heads/release/1.x to 460964618e9c78456db66667b8503c2de2499874
✔ Successfully updated reference release-please--branches--refs/heads/release/1.x to 460964618e9c78456db66667b8503c2de2499874
Error: release-please failed: Validation Failed: {"resource":"PullRequest","field":"head","code":"invalid"}
```
