### ISSUE TITLE
Release PR opened for `chore`

### ISSUE THREAD

**Issue by remarkablemark** [google-github-actions/release-please-action#808]
### TL;DR

I made a commit with the `chore` type and Release Please opened a PR: https://github.com/remarkablemark/php-composer-test/pull/2. Is this expected behavior?

### Expected behavior

Release PR is not opened for type `chore`

### Observed behavior

Release PR opened for type `chore`

### Action YAML

```yaml
name: release-please
on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: php
```

https://github.com/remarkablemark/php-composer-test/blob/master/.github/workflows/release-please.yml
