### ISSUE TITLE
Can release please also include the dist folder on tag which is create on build

### ISSUE THREAD

**Issue by SiddHyper** [google-github-actions/release-please-action#810]
### TL;DR

Is there a way to add dist folder to tag created by release please

For example in my case I don't want to publish lib to npm I just want it to add dist folder to tags create in github repo

**Comment by audunru** [comment]
The Github action TriPSs/conventional-changelog-action has a [pre-commit hook](https://github.com/TriPSs/conventional-changelog-action#pre-commit-hook) that you can run, any files created will be added to the new release commit. I transitioned from that action to release-please and I'm looking for something to replace that hook I used to use. Is that what you're thinking of?

**Comment by audunru** [comment]
@SiddHyper Perhaps this is of help.

First release-please-action does its thing, then if a PR is created/updated I checkout the PR branch and build and commit updated files from the folder `public/build` to it.

The release-please PR then contains the updated package.json/package-lock.json _and_ the updated frontend build. If I then checkout the new version tag, that commit contains updated package.json and the new frontend build.

I got this to work about 10 minutes ago, so there might be problems I don't know about.

```yml
name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: node

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.pr }}
        with:
          ref: ${{ fromJSON(steps.release.outputs.pr).headBranchName }}

      - name: Use Node v20
        uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.pr }}
        with:
          node-version: "20"
          cache: "npm"

      - run: npm ci
        if: ${{ steps.release.outputs.pr }}

      - run: npm run build
        if: ${{ steps.release.outputs.pr }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        if: ${{ steps.release.outputs.pr }}
        with:
          commit_message: "chore: build frontend"
          file_pattern: "public/build"
```
