### ISSUE TITLE
Empty output when path is defined

### ISSUE THREAD

**Issue by furlangiacomo** [google-github-actions/release-please-action#811]
### TL;DR

If i create a release from a specific path that is not the root path then outputs like `tag_name` or `patch` are empty.

### Expected behavior

```
  echo "releases_created=$(echo true)" >> $GITHUB_OUTPUT
  echo "major=$(echo 1)" >> $GITHUB_OUTPUT
  echo "minor=$(echo 1)" >> $GITHUB_OUTPUT
  echo "patch=$(echo 1)" >> $GITHUB_OUTPUT
  echo "tag_name=$(echo v1.1.1)" >> $GITHUB_OUTPUT
```

### Observed behavior

```
  echo "releases_created=$(echo true)" >> $GITHUB_OUTPUT
  echo "major=$(echo )" >> $GITHUB_OUTPUT
  echo "minor=$(echo )" >> $GITHUB_OUTPUT
  echo "patch=$(echo )" >> $GITHUB_OUTPUT
  echo "tag_name=$(echo )" >> $GITHUB_OUTPUT
```

### Action YAML

```yaml
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.create_output.outputs.releases_created }}
      major: ${{ steps.create_output.outputs.major }}
      minor: ${{ steps.create_output.outputs.minor }}
      patch: ${{ steps.create_output.outputs.patch }}
      tag_name: ${{ steps.create_output.outputs.tag_name }}
    steps:
      - name: "Run release-please"
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          path: docker/tools
          package-name: tools

      - name: "Generate output"
        id: create_output
        shell: bash
        run: |
            echo "releases_created=$(echo ${{ steps.release.outputs.releases_created }})" >> $GITHUB_OUTPUT
            echo "major=$(echo ${{ steps.release.outputs.major }})" >> $GITHUB_OUTPUT
            echo "minor=$(echo ${{ steps.release.outputs.minor }})" >> $GITHUB_OUTPUT
            echo "patch=$(echo ${{ steps.release.outputs.patch }})" >> $GITHUB_OUTPUT
            echo "tag_name=$(echo ${{ steps.release.outputs.tag_name }})" >> $GITHUB_OUTPUT
```
