### ISSUE TITLE
release-please fails to create a tag

### ISSUE THREAD

**Issue by emmanuel-apau** [google-github-actions/release-please-action#817]
### TL;DR

i setup a simple release configuration with a version file and changelog but when the PR is merged it doesn't remove the label `autorelease: pending` and never creates a tag.

It errors out in the logs

### Expected behavior

a tag is created

### Observed behavior

no tag was created but the changelog and version where bumped

### Action YAML

```yaml
---
name: Automate Tagging

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          command: release-pr
          include-v-in-tag: false
```

### Log output

```text
Run google-github-actions/release-please-action@v3
✔ Looking for latest release on branch: main with prefix: 
❯ Fetching merge commits on branch main with cursor: undefined
❯ Found latest release pull request: 26 version: 1.0.2
❯ Fetching releases with cursor undefined
❯ found release for  Version {
  major: 1,
  minor: 0,
  patch: 0,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found 1 possible releases. [
  Version {
    major: 1,
    minor: 0,
    patch: 2,
    preRelease: undefined,
    build: undefined
  }
]
✔ Building pull requests
✔ Building strategies by path
❯ .: simple
✔ Collecting release commit SHAs
❯ release search depth: 400
❯ Fetching releases with cursor undefined
⚠ Expected 1 releases, only found 0
⚠ Missing 1 paths: .
❯ looking for tagName: 1.0.2
⚠ Expected 1 releases, only found 0
✔ Collecting commits since all latest releases
❯ commit search depth: 500
❯ Set(0) {}
❯ Fetching merge commits on branch main with cursor: undefined
❯ Backfilling file list for commit:
❯ Found 4 files
..
❯ Backfilling file list for commit:
❯ Found 4 files
✔ Splitting 86 commits by path
✔ No latest release found for path: ., component: , but a previous version (1.0.2) was specified in the manifest.
✔ Building candidate release pull request for path: .
❯ type: simple
❯ targetBranch: main
❯ commit could not be parsed: 301e integrate google-github-actions/release-please-action into the repo (#21)
..
⚠ No latest release pull request found.
❯ commits: 7
✔ Considering: 7 commits
❯ component: 
❯ pull request title pattern: undefined
❯ Found pull request #26: 'chore(main): release 1.0.2'
⚠ There are untagged, merged release PRs outstanding - aborting
```
