### ISSUE TITLE
Schema is out of date

### ISSUE THREAD

**Issue by danielo515** [google-github-actions/release-please-action#828]
### TL;DR

If you run any linter that uses the schema of github actions, it says that the key `release-type` is required, but that is not true when yu use the command manifest.

### Action YAML

```yaml
on:
    push:
        branches:
            - master

permissions:
    contents: write
    pull-requests: write

name: Release
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Install Dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Release Please
              uses: google-github-actions/release-please-action@v3
              id: release
              with:
                command: manifest
                token: ${{secrets.GITHUB_TOKEN}}
                default-branch: main
```
