### ISSUE TITLE
Files aren't modified when using extra-files

### ISSUE THREAD

**Issue by foxted** [google-github-actions/release-please-action#831]
### TL;DR

I have extra YAML files that are setup to be modified in my `release-please-config.json` like so: 

```
"extra-files": [
        "README.md",
        {
          "type": "yaml",
          "path": ".github/workflows/build-push.yml",
          "jsonpath": "$.on.workflow_call.inputs.dx_branch.default"
        },
        {
          "type": "yaml",
          "path": ".github/workflows/deploy-gke.yml",
          "jsonpath": "$.on.workflow_call.inputs.dx_branch.default"
        },
        {
          "type": "yaml",
          "path": ".github/workflows/deploy-openshift.yml",
          "jsonpath": "$.on.workflow_call.inputs.dx_branch.default"
        },
        {
          "type": "yaml",
          "path": ".github/workflows/validate.yml",
          "jsonpath": "$.on.workflow_call.inputs.dx_branch.default"
        }
      ]
```

When running locally, the files are being modified accordingly: 

```
...
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).
updates: 8
❯ Fetching CHANGELOG.md from branch main
❯ Fetching version.txt from branch main
⚠ file version.txt did not exist
❯ Fetching README.md from branch main
❯ Fetching .github/workflows/build-push.yml from branch main
❯ Fetching .github/workflows/deploy-gke.yml from branch main
❯ Fetching .github/workflows/deploy-openshift.yml from branch main
❯ Fetching .github/workflows/validate.yml from branch main
❯ Fetching .release-please-manifest.json from branch main
  CHANGELOG.md:  [class Changelog extends DefaultUpdater]
  version.txt:  [class DefaultUpdater]
  README.md:  [class Generic extends DefaultUpdater]
  .github/workflows/build-push.yml:  [class GenericYaml]
  .github/workflows/deploy-gke.yml:  [class GenericYaml]
  .github/workflows/deploy-openshift.yml:  [class GenericYaml]
  .github/workflows/validate.yml:  [class GenericYaml]
  .release-please-manifest.json:  [class ReleasePleaseManifest extends DefaultUpdater]
```

But when using this GitHub Action, these files aren't being updated at all.

### Expected behavior

Files set in extra-files should be modified accordingly. 

### Observed behavior

FIles aren't being modified, only the CHANGELOG.md and version.txt are.

### Action YAML

```yaml
name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Release Please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple

      - name: Tag major and minor versions
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git remote add gh-token "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ env.GITHUB_REPOSITORY }}.git"
          git tag -d v${{ steps.release.outputs.major }} || true
          git tag -d v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
          git push origin :v${{ steps.release.outputs.major }} || true
          git push origin :v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
          git tag -a v${{ steps.release.outputs.major }} -m "Release v${{ steps.release.outputs.major }}"
          git tag -a v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} -m "Release v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}"
          git push origin v${{ steps.release.outputs.major }}
          git push origin v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}
```

### Log output

```text
14s
Run google-github-actions/release-please-action@main
  with:
    release-type: simple
    command: release-pr
    token: ***
    fork: false
    clean: true
    bump-minor-pre-major: false
    bump-patch-for-minor-pre-major: false
    changelog-host: https://github.com
    github-api-url: https://api.github.com
    github-graphql-url: https://api.github.com/graphql
    monorepo-tags: false
✔ Looking for latest release on branch: main with prefix: 
❯ Fetching merge commits on branch main with cursor: undefined
❯ Found latest release pull request: 110 version: 2.12.0
❯ Fetching releases with cursor undefined
❯ found release for  Version {
  major: 2,
  minor: 12,
  patch: 0,
  preRelease: undefined,
  build: undefined
}
❯ found release for  Version {
  major: 2,
  minor: 11,
  patch: 0,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found release for  Version {
  major: 2,
  minor: 10,
  patch: 3,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found release for  Version {
  major: 2,
  minor: 10,
  patch: 2,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found release for  Version {
  major: 2,
  minor: 10,
  patch: 1,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found release for  Version {
  major: 2,
  minor: 10,
  patch: 0,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found release for  Version {
  major: 2,
  minor: 9,
  patch: 2,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found release for  Version {
  major: 2,
  minor: 9,
  patch: 1,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found release for  Version {
  major: 2,
  minor: 9,
  patch: 0,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found release for  Version {
  major: 2,
  minor: 8,
  patch: 7,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found release for  Version {
  major: 2,
  minor: 8,
  patch: 6,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found release for  Version {
  major: 2,
  minor: 8,
  patch: 5,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found release for  Version {
  major: 2,
  minor: 8,
  patch: 4,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found release for  Version {
  major: 2,
  minor: 8,
  patch: 3,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found release for  Version {
  major: 2,
  minor: 8,
  patch: 2,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found release for  Version {
  major: 2,
  minor: 8,
  patch: 1,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found release for  Version {
  major: 2,
  minor: 8,
  patch: 0,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found release for  Version {
  major: 2,
  minor: 7,
  patch: 1,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found release for  Version {
  major: 2,
  minor: 7,
  patch: 0,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found release for  Version {
  major: 2,
  minor: 6,
  patch: 0,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found release for  Version {
  major: 2,
  minor: 5,
  patch: 6,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found release for  Version {
  major: 2,
  minor: 5,
  patch: 5,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found release for  Version {
  major: 2,
  minor: 5,
  patch: 4,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found release for  Version {
  major: 2,
  minor: 5,
  patch: 3,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found release for  Version {
  major: 2,
  minor: 5,
  patch: 2,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ Fetching releases with cursor Y3Vyc29yOnYyOpK0MjAyMy0wMy0yNFQyMjo1OToyN1rOBcY9YQ==
❯ found release for  Version {
  major: 2,
  minor: 5,
  patch: 1,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found release for  Version {
  major: 2,
  minor: 5,
  patch: 0,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found release for  Version {
  major: 2,
  minor: 4,
  patch: 1,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found release for  Version {
  major: 2,
  minor: 4,
  patch: 0,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found release for  Version {
  major: 2,
  minor: 3,
  patch: 0,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found release for  Version {
  major: 2,
  minor: 2,
  patch: 0,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found release for  Version {
  major: 2,
  minor: 1,
  patch: 0,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found release for  Version {
  major: 2,
  minor: 0,
  patch: 0,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found release for  Version {
  major: 1,
  minor: 1,
  patch: 0,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found release for  Version {
  major: 1,
  minor: 0,
  patch: 0,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found 2 possible releases. [
  Version {
    major: 2,
    minor: 12,
    patch: 0,
    preRelease: undefined,
    build: undefined
  },
  Version {
    major: 2,
    minor: 12,
    patch: 0,
    preRelease: undefined,
    build: undefined
  }
]
✔ Building pull requests
✔ Building strategies by path
❯ .: simple
✔ Collecting release commit SHAs
❯ release search depth: 400
❯ Fetching releases with cursor undefined
❯ Found release for path ., v2.12.0
❯ release for path: ., version: 2.12.0, sha: a241353f18f82f8444b7c35fbafeb5aa88a5a7f7
✔ Collecting commits since all latest releases
❯ commit search depth: 500
❯ Set(1) { 'a241353f18f82f8444b7c35fbafeb5aa88a5a7f7' }
❯ Fetching merge commits on branch main with cursor: undefined
❯ Backfilling file list for commit: 85ae6de4d49f5201f0826f0f80413e2429da50a4
❯ Found 1 files
❯ Backfilling file list for commit: 4492d672cf18488ddefd9f81124fb9a2d4cecc18
❯ Found 1 files
❯ Backfilling file list for commit: bd000d6d388553adbcf943dee2acc5a9cd5be57d
❯ Found 1 files
❯ Backfilling file list for commit: 85443c6d4ff5f020d5b8c30a2d28e92e7fa7969a
❯ Found 0 files
❯ Backfilling file list for commit: bba17eaced39f757e4feef3d4eaa09d126c5ba6e
❯ Found 0 files
❯ Backfilling file list for commit: f6fd1675d4fc68d106aa1e65f092c312ba3d97f9
❯ Found 1 files
❯ Backfilling file list for commit: 9a58349ea5c1c9fd45182ff04da64a471ebc0bfb
❯ Found 1 files
❯ Backfilling file list for commit: 30744ad18786fd27da12f74b3673c5b2242b090c
❯ Found 2 files
❯ Backfilling file list for commit: aa79b8eef53d5f71e1a8b6994ebc4aa342d63af2
❯ Found 1 files
❯ Backfilling file list for commit: 94f1c2cfec49396bf4ba0081e1c3f4c331127419
❯ Found 5 files
❯ Backfilling file list for commit: 3815f6fad3dd50bf7c4566b56c0f6f73d9743194
❯ Found 0 files
❯ Backfilling file list for commit: 666565c4bd0f6651b146936b785a677df8f12f4b
❯ Found 1 files
❯ Backfilling file list for commit: 9378652e3da9e4f5e34edb09b9e413421c293b26
❯ Found 1 files
❯ Backfilling file list for commit: 14664adada3845450595893889e8d4a2463f43f8
❯ Found 1 files
❯ Backfilling file list for commit: c26ff55935b391e6798a7e93eeddcfe3c5932c6d
❯ Found 0 files
❯ Backfilling file list for commit: 6066fbf757439d5763407ecb951c749b622ff175
❯ Found 1 files
✔ Splitting 4 commits by path
✔ Building candidate release pull request for path: .
❯ type: simple
❯ targetBranch: main
❯ commits: 4
✔ Considering: 4 commits
❯ component: 
❯ pull request title pattern: undefined
✔ Looking for open release pull requests
✔ found 1 open release pull requests.
✔ Looking for snoozed release pull requests
✔ found 0 snoozed release pull requests.
❯ Fetching CHANGELOG.md from branch main
❯ Fetching version.txt from branch main
⚠ file version.txt did not exist
❯ Fetching .release-please-manifest.json from branch main
✔ Starting GitHub PR workflow...
✔ Successfully found branch HEAD sha "85ae6de4d49f5201f0826f0f80413e2429da50a4".
✔ Skipping branch creation step...
✔ Got the latest commit tree
✔ Successfully created a tree with the desired changes with SHA 28427c39d7ecc946d973e3c22cde6409205b1a82
✔ Successfully created commit. See commit at https://api.github.com/repos/org/repo/git/commits/e7ebc753974837360a565b909c29215e4bac6bd0
✔ Updating reference heads/release-please--branches--main to e7ebc753974837360a565b909c29215e4bac6bd0
✔ Successfully updated reference release-please--branches--main to e7ebc753974837360a565b909c29215e4bac6bd0
✔ Found existing pull request for reference org:release-please--branches--main. Skipping creating a new pull request.
✔ Successfully opened pull request: 112.
```
