### ISSUE TITLE
No tag if setting release to draft

### ISSUE THREAD

**Issue by arvnik** [google-github-actions/release-please-action#833]
### TL;DR

Hi! It seems that the tag is not properly created and pushed if I set the draft parameter to true. Changelog looks correct and release is created as expected but the tag isn't there.

### Action YAML

```yaml
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Release Please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
          token: ${{ token }}
          include-v-in-tag: false
          draft-pull-request: true
          draft: true
```
