### ISSUE TITLE
release-please failed: API rate limit exceeded for installation ID 5801625. If you reach out to GitHub Support for help, please include the request ID 50C1:12C8:12B1335:26CF48D:6552F45E.

### ISSUE THREAD

**Issue by zerotn3** [google-github-actions/release-please-action#866]
### TL;DR

```yaml
bump-version:
    name: Bump version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bump version
        uses: google-github-actions/release-please-action@v3
        id: release-version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          monorepo-tags: true # use monorepo tags
          bump-minor-pre-major: true # bump minor version if there is a pre-major version
          bump-patch-for-minor-pre-major: true # bump patch version if there is a pre-major version
          release-type: node # release type
```
im using like config above for each push request. But I always got: release-please failed: API rate limit exceeded for installation. Please help me with how to avoid them. Thank you

### Action YAML

```yaml
bump-version:
    name: Bump version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bump version
        uses: google-github-actions/release-please-action@v3
        id: release-version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          monorepo-tags: true # use monorepo tags
          bump-minor-pre-major: true # bump minor version if there is a pre-major version
          bump-patch-for-minor-pre-major: true # bump patch version if there is a pre-major version
          release-type: node # release type
```
