### ISSUE TITLE
502 errors, not clear why it fails

### ISSUE THREAD

**Issue by legremz** [google-github-actions/release-please-action#867]
### TL;DR

My Actions pipeline fails sometime with no clear information on the cause.
Hard to reproduce and no clear error message to allow quick debug.

### Expected behavior

Do a release process

### Observed behavior

Fail and return generic message that doesn't help debuging

### Action YAML

```yaml
releaser:
    name: Releaser
    runs-on: ubuntu-latest
    needs: [helm, docker]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          token: xxx
          sequential-calls: true
          release-search-depth: 200
          commit-search-depth: 250
```

### Log output

```text
Run google-github-actions/release-please-action@v3
  with:
    release-type: simple
    token: ***
    sequential-calls: true
    release-search-depth: 200
    commit-search-depth: 250
    fork: false
    clean: true
    bump-minor-pre-major: false
    bump-patch-for-minor-pre-major: false
    changelog-host: https://github.com
    github-api-url: https://api.github.com
    github-graphql-url: https://api.github.com/graphql
    monorepo-tags: false
✔ Looking for latest release on branch: main with prefix: 
❯ Fetching merge commits on branch main with cursor: undefined
✔ received 502 error, 5 attempts remaining
✔ received 502 error, 4 attempts remaining
✔ received 502 error, 3 attempts remaining
✔ received 502 error, 2 attempts remaining
✔ received 502 error, 1 attempts remaining
⚠ ran out of retries and response is required
Error: release-please failed: Unknown error: {"data":null,"errors":[{"message":"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `48A8:367F:0016:007E:65548D23` when reporting this issue."}]}
```

### Additional information

In an other action just before the run of the releaser, I log the API limits and I'm far for hitting the limits (99% of the quota is not used)
