### ISSUE TITLE
Comments are purged from extra files of type .yaml

### ISSUE THREAD

**Issue by DuncanCasteleyn** [google-github-actions/release-please-action#896]
### TL;DR

extra files option purges all comments since V4 from yaml files

### Expected behavior

Comments are retained

### Observed behavior

![image](https://github.com/google-github-actions/release-please-action/assets/10881109/35c66619-a54d-43d3-8679-60dc7766a5ff)

Comments including # x-release-please are removed.

### Action YAML

```yaml
jobs:
  release-please:
    runs-on: [ self-hosted, Ubuntu-20.04 ]
    permissions:
      contents: write
      pull-requests: write
```
