### ISSUE TITLE
Labels are not being applied from config JSON

### ISSUE THREAD

**Issue by abhi-markan** [google-github-actions/release-please-action#917]
### TL;DR

```json
{
    "$schema": "https://raw.githubusercontent.com/googleapis/release-please/main/schemas/config.json",
    "packages": {
        ".": {}
    },
    "pull-request-title-pattern": "chore(${scope}): release${component} ${version}",
    "extra-label": "Type: chore, Type: Docs",
    "extra-files": [
        "CHANGELOG.md"
    ]
}
```

Above `release-please-config.json` does not allow inclusion or addition of custom labels specified.

### Expected behavior

Expect the PR to have additional labels specified in the default config file.

### Observed behavior

Custom user labels are not added to the label, rather standard `autopending` label is attached to the PR.

### Action YAML

```yaml
name: Automated release
run-name: Executing release on ${{ github.repository }} 🚀

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  # 1. `package.json`, `README.md` and `CHANGELOG.md` updates
  release:
    name: Release setup 🔧
    runs-on: ubuntu-latest
    steps:
      - name: Release version ⚡️
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          release-type: node
          target-branch: main
```
