### ISSUE TITLE
prerelease not working

### ISSUE THREAD

**Issue by dinjazelena** [google-github-actions/release-please-action#925]
### TL;DR

```
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          release-type: python
          version-file: togusa/__init__.py
          prerelease: true
          prerelease-type: beta
```
Hi, so when i specify prerelease and prerelease type, nothing really happens it just creates regular Release and version bump.

I also get this warning:
Unexpected input(s) 'version-file', 'prerelease', 'prerelease-type', valid inputs are ['token', 'release-type', 'path', 'target-branch', 'config-file', 'manifest-file', 'repo-url', 'github-api-url', 'github-graphql-url', 'fork', 'include-component-in-tag', 'proxy-server', 'skip-github-release', 'skip-github-pull-request']

### Expected behavior

Create a prerelase with beta added to version

### Action YAML

```yaml
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          release-type: python
          version-file: togusa/__init__.py
          prerelease: true
          prerelease-type: beta
```
