### ISSUE TITLE
Error: release-please failed: Not Found (On repo working yesterday)

### ISSUE THREAD

**Issue by aaronware** [google-github-actions/release-please-action#928]
### TL;DR

Started happening this morning. Also tried generating a new token in case it had something to do with with that. However it threw the same error

### Expected behavior

Create a release

### Observed behavior

Error

### Action YAML

```yaml
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    if: github.event_name != 'pull_request' && github.event.pull_request.merged != true
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GH_BOT_TOKEN }}
```

### Log output

```text
Run google-github-actions/release-please-action@v4
Running release-please version: 16.5.0
❯ Fetching release-please-config.json from branch main
❯ Fetching .release-please-manifest.json from branch main
✔ Building releases
✔ Building strategies by path
❯ .: php
❯ Found pull request #44: 'chore(main): release 1.0.9'
✔ Building release for path: .
❯ type: php
❯ targetBranch: main
✔ Creating 1 releases for pull #44
Error: release-please failed: Not Found
```
