### ISSUE TITLE
How to use release please github action to hotfix

### ISSUE THREAD

**Issue by jfoo1984** [google-github-actions/release-please-action#930]
### TL;DR

I'm wondering if it is possible to use this action to make hotfixes.  Essentially, this would involve cherry picking a fix PR commit merged to the `main` branch onto specific release tags (the release tags that are deployed to our staging and production environments).

**Comment by raja-anbazhagan** [comment]
Is this even possible?

**Comment by axel-havukangas-tt** [comment]
According to the [documentation](https://github.com/googleapis/release-please-action/blob/main/README.md#supporting-multiple-release-branches), you can use different target branches for different releases. So in your github action you could have something like

```yaml
on:
  push:
    branches:
      - main
      - 'hotfix/**'
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: node
          # The short ref name of the branch or tag that triggered
          #  the workflow run. For example, `main` or `hotfix/urgent-bugfix`
          target-branch: ${{ github.ref_name }}
```

this should then create separate release PRs for each branch that triggers the action.
