### ISSUE TITLE
After merging a release PR, a release is created but then another release PR is automatically opened

### ISSUE THREAD

**Issue by megancoyle** [google-github-actions/release-please-action#962]
### TL;DR

When using the release-please action, on triggering a release PR, if I merge in the release PR, a release will get created in the draft format, but a duplicate release PR will get opened

Here's an example of what the `.release-please-manifest.json` looks like:
```
{
  ".": "1.0.3"
}
```

Here's what the `release-please-config.json` looks like:
```
{
  "packages": {
    ".": {
      "release-type": "node",
      "draft": true,
      "include-component-in-tag": false
    }
  },
  "$schema": "https://raw.githubusercontent.com/googleapis/release-please/main/schemas/config.json"
}
```

### Expected behavior

After merging in a release PR, I was expecting a draft release to get created, and no other PR get automatically opened.

### Observed behavior

Instead, a duplicate release PR of the one just merged, was getting opened.

### Action YAML

```yaml
name: Run release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use latest release-please action
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
```
