### ISSUE TITLE
Release-please fails to create tags/release

### ISSUE THREAD

**Issue by RazvanCretu** [google-github-actions/release-please-action#968]
### TL;DR

I have tried release-please v3/4 and literally none of them are working. I get a PR created but no tag/release.

It only worked like 3 times on v3 but for the past 5h it drove me nuts as I have rerun for over 40 times with different configs and nothing...

> Please note that it had ran on an Enterprise Server with a self-hosted runner and on a windows machine!!!

### Expected behavior

To work I guess..

### Observed behavior

I couldn't find anything suspicious as actions logs don't throw errors related to failed creation of tags/releases

The run looks susccessful in github

### Action YAML

```yaml
jobs:
  ci-cd:
    runs-on: [self-hosted, win-machine]
    steps:
      - name: release
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{secrets.GH_TOKEN}}
          default-branch: main
          release-type: node
```

### Log output

```text
Sorry, i can't paste it here as I work on an Enterprise Server and it is very restricted. I don't have access to github.com
```
