### ISSUE TITLE
Missing required file: package.json when using path config

### ISSUE THREAD

**Issue by evtk** [google-github-actions/release-please-action#974]
### TL;DR

The package I want to create a release for is in a subfolder `aws`. 
I configured the path option in the release-please action, but I get an error.

### Expected behavior

No errors

### Observed behavior

release-please failed: node (my-repo-name): Missing required file: package.json

### Action YAML

```yaml
steps:
      - id: release
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: node
          path: ./aws
```
```


### Log output

_No response_

### Additional information

_No response_

**Comment by joshghent** [comment]
Got this same problem.

**Comment by hasithaishere** [comment]
Faced same problem

**Comment by evtk** [comment]
I was able to fix it with by following these guidelines: https://github.com/google-github-actions/release-please-action?tab=readme-ov-file#upgrading-from-v3-to-v4

and configuring the path in `release-please-config.json` like this:

```
{
  "packages": {
    "aws": {
      "release-type": "node"
    }
  }
}
```

and creating the `.release-please-manifest.json` like this.

```
{
  "aws": "1.0.0"
}
```

But the documentation clearly puts you on the wrong track for this. Also it seems it creates some sort of sub-package 'aws' which isn't exactly what I was looking for, but it solves it for now.

**Comment by samdouble** [comment]
In your action yaml file `release-type` has to be `simple`, not `node`.

So:
**action.yml**
```
steps:
      - id: release
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: simple
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
```

**release-please-config.json**
{
  "packages": {
    "aws": {
      "release-type": "node"
    }
  }
}

**.release-please-manifest.json**
```
{
  "aws": "1.0.0"
}
```
