### ISSUE TITLE
Eroor when trying to release

### ISSUE THREAD

**Issue by oktayalizada** [google-github-actions/release-please-action#977]
### TL;DR

Cannot release an artifact. Pipeline was working few hours ago but stopped working with "Something went wrong" 

### Expected behavior

Creates tag, adds Changelog and Releases artifact

### Observed behavior

Getting an error:
```

✔ Building strategies by path
❯ .: elixir
✔ Collecting release commit SHAs
❯ release search depth: 400
❯ Fetching releases with cursor undefined
⚠ Could not find releases.
⚠ Expected 1 releases, only found 0
⚠ Missing 1 paths: .
❯ looking for tagName: v0.0.1
⚠ Expected 1 releases, only found 0
✔ Collecting commits since all latest releases
❯ commit search depth: 500
❯ Set(0) {}
❯ Fetching merge commits on branch main with cursor: undefined
Error: release-please failed: Request failed due to following response errors:
 - Something went wrong while executing your query. Please include `A885:390BA2:701B762:B9807B8:663A407E` when reporting this issue.
```

### Action YAML

```yaml
name: Release

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "*"
jobs:
  release:
    if: contains(github.event.head_commit.message, 'release-please--branches') || startsWith(github.event.head_commit.message, 'bump')
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PEM }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: "${{ steps.generate_token.outputs.token }}"
          manifest-file: .release-please-manifest.json
          config-file: release-please-config.json
```
